// ====== BANQUE DE QUESTIONS « BATTLE » ======
// Chaque Battle tire 2 questions « quotidien », 1 « souvenir » et 2 « coquin ».
// Le but n'est pas d'avoir raison : c'est de répondre la même chose que l'autre.
//
// Chaque question porte un identifiant stable : l'app retient celles déjà
// sorties (rooms/$room/battleVues) et ne les repropose qu'une fois la
// catégorie entièrement épuisée. Deux Battles ne peuvent donc pas se recouper.
//
// Vous pouvez enrichir cette banque depuis l'onglet Cartes de l'app
// (les questions ajoutées vivent dans Firebase, pas dans ce fichier).

const BATTLE_QUESTIONS = [

  // ================= COMPLICITÉ DU QUOTIDIEN =================
  { id:'q001', cat:'quotidien', q:"Notre soirée idéale à deux, c'est plutôt…", a:["Canapé, plaid et série","Un bon restaurant","Recevoir des amis","Une sortie improvisée"] },
  { id:'q002', cat:'quotidien', q:"Le plat qu'on commande les yeux fermés ?", a:["Pizza","Sushis","Burger","Un plat mijoté maison"] },
  { id:'q003', cat:'quotidien', q:"Qui craque le premier devant un dessert ?", a:["Moi, sans hésiter","Toi, évidemment","Les deux en même temps","Ni l'un ni l'autre"] },
  { id:'q004', cat:'quotidien', q:"Le dimanche matin parfait ?", a:["Grasse matinée","Petit déj au lit","Balade au marché","Sport et bonne conscience"] },
  { id:'q005', cat:'quotidien', q:"Ce qui nous fait le plus rire ensemble ?", a:["Nos private jokes","Les gens autour de nous","Un bon film comique","Nos propres bêtises"] },
  { id:'q006', cat:'quotidien', q:"Qui est le plus bordélique à la maison ?", a:["Moi","Toi","Autant l'un que l'autre","Personne, on est nickel"] },
  { id:'q007', cat:'quotidien', q:"Notre pire corvée ménagère ?", a:["Le repassage","La vaisselle","Passer l'aspirateur","Nettoyer la salle de bain"] },
  { id:'q008', cat:'quotidien', q:"Un dimanche sans obligations, on fait quoi ?", a:["Au lit le plus longtemps possible","Une escapade à deux","Un gros projet maison","Chacun sa bulle"] },
  { id:'q009', cat:'quotidien', q:"Qui décide vraiment du film qu'on regarde ?", a:["Moi","Toi","On négocie","On finit par ne rien regarder"] },
  { id:'q010', cat:'quotidien', q:"Notre boisson de couple ?", a:["Un bon verre de vin","Une bière fraîche","Un cocktail","Un thé ou un café"] },
  { id:'q011', cat:'quotidien', q:"Qui râle le plus le matin ?", a:["Moi","Toi","Les deux","Personne, on est du matin"] },
  { id:'q012', cat:'quotidien', q:"La petite attention qui fait toujours mouche ?", a:["Un message inattendu","Un câlin sans raison","Son plat préféré","La grasse matinée offerte"] },
  { id:'q013', cat:'quotidien', q:"Notre dispute la plus récurrente porte sur…", a:["Le rangement","Les horaires et les retards","L'argent","On ne se dispute pas vraiment"] },
  { id:'q014', cat:'quotidien', q:"Qui conduit quand on part loin ?", a:["Moi","Toi","On alterne","Le moins fatigué"] },
  { id:'q015', cat:'quotidien', q:"Le truc qu'on remet toujours à demain ?", a:["Le ménage à fond","Trier les papiers","Prendre rendez-vous","Ranger le garage"] },
  { id:'q016', cat:'quotidien', q:"Notre façon de se réconcilier ?", a:["Un câlin et on n'en parle plus","On en discute vraiment","Un bon repas","L'humour désamorce tout"] },
  { id:'q017', cat:'quotidien', q:"Qui prend le plus de place dans le lit ?", a:["Moi","Toi","Les enfants ou l'animal","On est bien rangés"] },
  { id:'q018', cat:'quotidien', q:"1000 € tombent du ciel, on en fait quoi ?", a:["Un week-end à deux","On économise","Un truc pour la maison","Un cadeau chacun"] },
  { id:'q019', cat:'quotidien', q:"Qui vide le lave-vaisselle le plus souvent ?", a:["Moi","Toi","Chacun son tour","Celui qui craque en premier"] },
  { id:'q020', cat:'quotidien', q:"Le petit déjeuner idéal ?", a:["Sucré, tartines et confiture","Salé, œufs et bacon","Juste un café","Viennoiseries de la boulangerie"] },
  { id:'q021', cat:'quotidien', q:"Qui se couche le dernier ?", a:["Moi","Toi","On se couche ensemble","Ça dépend des soirs"] },
  { id:'q022', cat:'quotidien', q:"Le réveil du week-end, c'est plutôt…", a:["Avant 8 h","Entre 8 h et 9 h","Entre 9 h et 10 h","Le plus tard possible"] },
  { id:'q023', cat:'quotidien', q:"Qui passe le plus de temps sur son téléphone ?", a:["Moi","Toi","Autant tous les deux","On décroche facilement"] },
  { id:'q024', cat:'quotidien', q:"Notre série à regarder ensemble, c'est plutôt…", a:["Policier ou thriller","Comédie","Science-fiction","Documentaire"] },
  { id:'q025', cat:'quotidien', q:"Qui choisit la musique en voiture ?", a:["Moi","Toi","Chacun son tour","La radio décide"] },
  { id:'q026', cat:'quotidien', q:"Le meilleur moment de notre journée type ?", a:["Le café du matin","Le repas du soir","Le canapé après manger","Le moment du coucher"] },
  { id:'q027', cat:'quotidien', q:"Qui cuisine le mieux ?", a:["Moi","Toi","On est à égalité","Personne, soyons honnêtes"] },
  { id:'q028', cat:'quotidien', q:"Notre restaurant idéal ?", a:["Italien","Asiatique","Bistrot français","Un truc à tester au hasard"] },
  { id:'q029', cat:'quotidien', q:"Qui oublie le plus les dates importantes ?", a:["Moi","Toi","Aucun des deux","Les deux, c'est dramatique"] },
  { id:'q030', cat:'quotidien', q:"Le chauffage à la maison, c'est la guerre ?", a:["J'ai toujours froid","J'ai toujours chaud","On est d'accord","On n'y touche jamais"] },
  { id:'q031', cat:'quotidien', q:"Comment on gère les courses ?", a:["Ensemble chaque semaine","Un des deux s'en charge","Drive ou livraison","Au fil de l'eau"] },
  { id:'q032', cat:'quotidien', q:"Qui prend les décisions financières ?", a:["Moi","Toi","On décide ensemble","Personne, on improvise"] },
  { id:'q033', cat:'quotidien', q:"Le petit défaut de l'autre, avoué gentiment ?", a:["La lenteur","L'impatience","La tête en l'air","L'entêtement"] },
  { id:'q034', cat:'quotidien', q:"Notre activité de couple préférée ?", a:["Marcher ou randonner","Cuisiner","Regarder un film","Ne rien faire ensemble"] },
  { id:'q035', cat:'quotidien', q:"Qui répond le plus vite aux messages ?", a:["Moi","Toi","Les deux, instantanément","Aucun des deux"] },
  { id:'q036', cat:'quotidien', q:"L'état de nos placards, honnêtement ?", a:["Impeccable chez moi","Impeccable chez toi","Le chaos des deux côtés","On préfère ne pas regarder"] },
  { id:'q037', cat:'quotidien', q:"Un soir de flemme totale, on mange quoi ?", a:["Livraison","Pâtes au beurre","Restes du frigo","Apéro dînatoire"] },
  { id:'q038', cat:'quotidien', q:"Qui a le plus mauvais goût musical ?", a:["Moi","Toi","Aucun, on a les mêmes goûts","Les deux, différemment"] },
  { id:'q039', cat:'quotidien', q:"On part en week-end : qui fait les valises ?", a:["Moi","Toi","Chacun la sienne","À la dernière minute, ensemble"] },
  { id:'q040', cat:'quotidien', q:"Qui est le plus rancunier ?", a:["Moi","Toi","Aucun des deux","Les deux, un peu"] },
  { id:'q041', cat:'quotidien', q:"La douche, c'est plutôt…", a:["Le matin","Le soir","Les deux","Quand l'occasion se présente"] },
  { id:'q042', cat:'quotidien', q:"Notre pire habitude de couple ?", a:["Le téléphone à table","Se coucher fâchés","Trop de plateaux-repas","Ne jamais s'arrêter"] },
  { id:'q043', cat:'quotidien', q:"Qui perd le plus souvent ses clés ?", a:["Moi","Toi","Personne","Les deux, en même temps"] },
  { id:'q044', cat:'quotidien', q:"L'apéro parfait ?", a:["Charcuterie et fromage","Chips et cacahuètes","Tapas maison","Juste le verre, sans manger"] },
  { id:'q045', cat:'quotidien', q:"Qui gère les rendez-vous médicaux ?", a:["Moi","Toi","Chacun les siens","Personne, on repousse"] },
  { id:'q046', cat:'quotidien', q:"Notre saison préférée à deux ?", a:["Le printemps","L'été","L'automne","L'hiver"] },
  { id:'q047', cat:'quotidien', q:"Qui fait le plus de compliments ?", a:["Moi","Toi","Autant les deux","On devrait en faire plus"] },
  { id:'q048', cat:'quotidien', q:"Le sport, dans notre couple ?", a:["On en fait ensemble","Chacun le sien","Un seul en fait","On en parle, c'est tout"] },
  { id:'q049', cat:'quotidien', q:"Qui a le plus besoin de moments seul ?", a:["Moi","Toi","Autant les deux","Ni l'un ni l'autre"] },
  { id:'q050', cat:'quotidien', q:"Notre façon de fêter une bonne nouvelle ?", a:["Une bouteille","Un restaurant","Un cadeau","Un câlin et c'est tout"] },
  { id:'q051', cat:'quotidien', q:"Qui remarque en premier qu'il manque quelque chose ?", a:["Moi","Toi","Personne avant la panne","Les deux, trop tard"] },
  { id:'q052', cat:'quotidien', q:"Le café, à la maison, c'est…", a:["Machine à filtre","Capsules","Expresso broyeur","On ne boit pas de café"] },
  { id:'q053', cat:'quotidien', q:"Qui est le plus douillet quand il est malade ?", a:["Moi","Toi","Autant les deux","Aucun, on encaisse"] },
  { id:'q054', cat:'quotidien', q:"Notre rythme de vacances ?", a:["Tout organiser à l'avance","Improviser sur place","Un mélange des deux","On part rarement"] },
  { id:'q055', cat:'quotidien', q:"Qui parle le plus au téléphone ?", a:["Moi","Toi","Ni l'un ni l'autre","Les deux, beaucoup"] },
  { id:'q056', cat:'quotidien', q:"Le rangement de la voiture ?", a:["Impeccable","Correct","Une catastrophe","Ça dépend de la voiture"] },
  { id:'q057', cat:'quotidien', q:"Notre dessert préféré à partager ?", a:["Tiramisu","Fondant au chocolat","Tarte aux fruits","Glace"] },
  { id:'q058', cat:'quotidien', q:"Qui a le sommeil le plus lourd ?", a:["Moi","Toi","Les deux","Aucun, on se réveille pour un rien"] },
  { id:'q059', cat:'quotidien', q:"Un imprévu de dernière minute, on réagit comment ?", a:["On s'adapte tout de suite","On râle puis on s'adapte","On annule tout","Ça dépend de qui décide"] },
  { id:'q060', cat:'quotidien', q:"Qui fait le premier pas après une dispute ?", a:["Moi","Toi","Ça dépend du sujet","Le temps fait son travail"] },
  { id:'q061', cat:'quotidien', q:"Le meilleur cadeau à recevoir de l'autre ?", a:["Un objet choisi avec soin","Une expérience à deux","Du temps ensemble","Une surprise totale"] },
  { id:'q062', cat:'quotidien', q:"Qui prend le plus soin de son apparence ?", a:["Moi","Toi","Autant les deux","On a lâché l'affaire"] },
  { id:'q063', cat:'quotidien', q:"Notre sujet de conversation inépuisable ?", a:["Les projets","Les gens qu'on connaît","Le travail","La nourriture"] },
  { id:'q064', cat:'quotidien', q:"Le samedi soir idéal ?", a:["À la maison, tranquilles","Chez des amis","En sortie tous les deux","Un dîner en famille"] },
  { id:'q065', cat:'quotidien', q:"Qui garde le plus longtemps ses vieux vêtements ?", a:["Moi","Toi","Les deux","Aucun, on trie souvent"] },
  { id:'q066', cat:'quotidien', q:"Notre pire achat commun ?", a:["Un appareil jamais utilisé","Un meuble mal choisi","Un truc trop cher","On n'a jamais mal acheté"] },
  { id:'q067', cat:'quotidien', q:"Qui remplit le frigo ?", a:["Moi","Toi","Chacun ses envies","Il n'est jamais rempli"] },
  { id:'q068', cat:'quotidien', q:"Comment on se dit bonne nuit ?", a:["Un bisou","Un câlin","Un simple mot","Souvent rien, on dort déjà"] },
  { id:'q069', cat:'quotidien', q:"Qui gère la paperasse administrative ?", a:["Moi","Toi","On partage","Personne, ça s'entasse"] },
  { id:'q070', cat:'quotidien', q:"Notre façon de décorer la maison ?", a:["Chaleureux et cosy","Épuré et moderne","Un peu de tout","On ne décore pas vraiment"] },
  { id:'q071', cat:'quotidien', q:"Qui est le plus stressé par les départs ?", a:["Moi","Toi","Autant les deux","Personne, on est zen"] },
  { id:'q072', cat:'quotidien', q:"Le film qu'on peut revoir cent fois ?", a:["Une comédie culte","Un grand classique","Un film d'action","Un film de Noël"] },
  { id:'q073', cat:'quotidien', q:"Qui mange le plus vite ?", a:["Moi","Toi","Les deux","On prend notre temps"] },
  { id:'q074', cat:'quotidien', q:"Notre rituel du dimanche soir ?", a:["Préparer la semaine","Un bon film","Un repas simple","On n'a pas de rituel"] },
  { id:'q075', cat:'quotidien', q:"Qui a le plus de mal à dire non ?", a:["Moi","Toi","Les deux","Aucun, on sait refuser"] },
  { id:'q076', cat:'quotidien', q:"On se dispute plutôt…", a:["Fort et vite fini","En silence","Rarement mais longtemps","On ne se dispute presque pas"] },
  { id:'q077', cat:'quotidien', q:"Qui a le plus d'applications inutiles sur son téléphone ?", a:["Moi","Toi","Les deux","Aucun, on fait le tri"] },
  { id:'q078', cat:'quotidien', q:"Notre plaisir coupable commun ?", a:["Une émission de télé-réalité","Le fast-food","Traîner au lit","Commander en ligne"] },
  { id:'q079', cat:'quotidien', q:"Qui prend les plus longues douches ?", a:["Moi","Toi","Autant les deux","On est rapides"] },
  { id:'q080', cat:'quotidien', q:"L'organisation des vacances, c'est…", a:["Moi qui gère","Toi qui gères","À deux","Personne, on part au dernier moment"] },
  { id:'q081', cat:'quotidien', q:"Qui a le plus besoin de silence pour se concentrer ?", a:["Moi","Toi","Les deux","Aucun, le bruit ne gêne pas"] },
  { id:'q082', cat:'quotidien', q:"Notre boisson chaude du soir ?", a:["Tisane","Thé","Chocolat chaud","Rien, on boit de l'eau"] },
  { id:'q083', cat:'quotidien', q:"Qui range en marchant, sans y penser ?", a:["Moi","Toi","Aucun des deux","Les deux"] },
  { id:'q084', cat:'quotidien', q:"Le pire moment de la semaine ?", a:["Le lundi matin","Le dimanche soir","Le mercredi","Aucun, tout va bien"] },
  { id:'q085', cat:'quotidien', q:"Qui a le plus de patience avec les autres ?", a:["Moi","Toi","Autant les deux","Aucun, franchement"] },
  { id:'q086', cat:'quotidien', q:"Notre façon d'aborder un gros achat ?", a:["On compare longuement","Coup de cœur assumé","On attend les soldes","On repousse indéfiniment"] },
  { id:'q087', cat:'quotidien', q:"Qui chante sous la douche ?", a:["Moi","Toi","Les deux","Personne"] },
  { id:'q088', cat:'quotidien', q:"Le rangement du salon avant une visite ?", a:["Panique générale","Un coup rapide","Il est déjà propre","On assume le désordre"] },
  { id:'q089', cat:'quotidien', q:"Qui se souvient le mieux des anniversaires des autres ?", a:["Moi","Toi","Le téléphone s'en charge","Personne"] },
  { id:'q090', cat:'quotidien', q:"Notre manière de passer une soirée pluvieuse ?", a:["Film et couverture","Jeu de société","Cuisine à deux","Chacun son écran"] },
  { id:'q091', cat:'quotidien', q:"Qui a le plus de mal à se lever ?", a:["Moi","Toi","Les deux","Aucun, on saute du lit"] },
  { id:'q092', cat:'quotidien', q:"Le petit truc de l'autre qui attendrit le plus ?", a:["Sa façon de rire","Ses manies","Sa voix du matin","Son regard"] },
  { id:'q093', cat:'quotidien', q:"Qui commence les phrases de l'autre ?", a:["Moi","Toi","Les deux","Aucun, on se laisse parler"] },
  { id:'q094', cat:'quotidien', q:"Notre position devant la télé ?", a:["Collés l'un à l'autre","Chacun son bout de canapé","L'un allongé sur l'autre","Ça change selon les soirs"] },
  { id:'q095', cat:'quotidien', q:"Qui aime le plus recevoir du monde ?", a:["Moi","Toi","Les deux","Aucun, on préfère être tranquilles"] },
  { id:'q096', cat:'quotidien', q:"Le rangement des photos de vacances ?", a:["Triées et classées","Tout en vrac sur le téléphone","Imprimées parfois","On ne les regarde jamais"] },
  { id:'q097', cat:'quotidien', q:"Qui dit le plus souvent « je t'aime » ?", a:["Moi","Toi","Autant les deux","On le montre autrement"] },
  { id:'q098', cat:'quotidien', q:"Notre rapport aux réseaux sociaux ?", a:["On y est beaucoup","Un seul y est","On regarde sans publier","On s'en est éloignés"] },
  { id:'q099', cat:'quotidien', q:"Qui négocie le mieux ?", a:["Moi","Toi","Personne","Ça dépend de l'enjeu"] },
  { id:'q100', cat:'quotidien', q:"Le meilleur moment de la journée pour parler sérieusement ?", a:["Le matin","Pendant le repas","Le soir au lit","En voiture"] },
  { id:'q101', cat:'quotidien', q:"Qui est le plus tête en l'air en cuisine ?", a:["Moi","Toi","Les deux","Aucun, on maîtrise"] },
  { id:'q102', cat:'quotidien', q:"Notre façon de gérer les enfants ou les proches ?", a:["Moi le souple, toi le strict","L'inverse","On est sur la même ligne","Ça varie selon les jours"] },
  { id:'q103', cat:'quotidien', q:"Le geste qui rassure le plus ?", a:["Une main dans le dos","Un baiser sur le front","Se tenir la main","Un simple regard"] },
  { id:'q104', cat:'quotidien', q:"Qui abandonne le premier un livre ennuyeux ?", a:["Moi","Toi","Aucun, on finit toujours","On ne lit pas"] },
  { id:'q105', cat:'quotidien', q:"Notre plat du dimanche ?", a:["Rôti ou volaille","Barbecue","Pâtes ou risotto","Restes améliorés"] },
  { id:'q106', cat:'quotidien', q:"Qui parle le plus dans un dîner à plusieurs ?", a:["Moi","Toi","Autant les deux","Aucun, on écoute"] },
  { id:'q107', cat:'quotidien', q:"Le bruit de l'autre qui agace le plus ?", a:["Le ronflement","Manger bruyamment","Pianoter sur le téléphone","Rien, franchement"] },
  { id:'q108', cat:'quotidien', q:"Qui prend le plus soin des plantes ?", a:["Moi","Toi","Personne, elles meurent","On n'en a pas"] },
  { id:'q109', cat:'quotidien', q:"Notre façon de choisir un restaurant ?", a:["Les avis en ligne","Le hasard","Toujours les mêmes adresses","Celui qui a de la place"] },
  { id:'q110', cat:'quotidien', q:"Qui craque le premier sur un achat plaisir ?", a:["Moi","Toi","Les deux","Aucun, on se raisonne"] },
  { id:'q111', cat:'quotidien', q:"Comment on s'appelle au quotidien ?", a:["Par nos prénoms","Par des surnoms","Par des petits mots doux","Ça change tout le temps"] },
  { id:'q112', cat:'quotidien', q:"Qui supporte le mieux la chaleur ?", a:["Moi","Toi","Les deux","Aucun, on fond"] },
  { id:'q113', cat:'quotidien', q:"Le premier réflexe en rentrant à la maison ?", a:["Se changer","Regarder le frigo","Se poser sur le canapé","Allumer la musique ou la télé"] },
  { id:'q114', cat:'quotidien', q:"Qui a le plus d'idées de sorties ?", a:["Moi","Toi","Autant les deux","Aucun, on manque d'idées"] },
  { id:'q115', cat:'quotidien', q:"Notre rapport au sucre ?", a:["Accros tous les deux","Un seul est accro","On se contrôle","On préfère le salé"] },
  { id:'q116', cat:'quotidien', q:"Qui se plaint le plus du travail ?", a:["Moi","Toi","Les deux","Aucun, on laisse ça au bureau"] },
  { id:'q117', cat:'quotidien', q:"Le meilleur endroit de la maison ?", a:["Le lit","Le canapé","La cuisine","Le jardin ou le balcon"] },
  { id:'q118', cat:'quotidien', q:"Qui a le plus besoin de lister les choses ?", a:["Moi","Toi","Les deux","Aucun, on garde tout en tête"] },
  { id:'q119', cat:'quotidien', q:"Notre façon de dire qu'on est fatigué ?", a:["On le dit clairement","On devient grognon","On s'endort devant la télé","On tient jusqu'au bout"] },
  { id:'q120', cat:'quotidien', q:"Qui fait le plus attention à ce qu'il mange ?", a:["Moi","Toi","Les deux","Aucun, on mange ce qu'on veut"] },
  { id:'q121', cat:'quotidien', q:"Le rangement de la salle de bain ?", a:["Mes affaires envahissent tout","Les tiennes envahissent tout","C'est équilibré","C'est le chaos"] },
  { id:'q122', cat:'quotidien', q:"Qui conduit le plus vite ?", a:["Moi","Toi","Les deux","Personne, on est prudents"] },
  { id:'q123', cat:'quotidien', q:"Notre façon de préparer une fête ?", a:["Tout prévoir à l'avance","Le jour même","Déléguer aux invités","On ne reçoit pas"] },
  { id:'q124', cat:'quotidien', q:"Qui est le plus superstitieux ?", a:["Moi","Toi","Aucun des deux","Les deux, un peu"] },
  { id:'q125', cat:'quotidien', q:"Le moment où on se sent le plus complices ?", a:["En voiture","Au lit","À table","En vacances"] },
  { id:'q126', cat:'quotidien', q:"Qui a la meilleure mémoire du couple ?", a:["Moi","Toi","Chacun se souvient de choses différentes","Aucun des deux"] },
  { id:'q127', cat:'quotidien', q:"Notre rapport aux animaux ?", a:["On en a et on adore","On en voudrait un","Un seul en veut","Sûrement pas"] },
  { id:'q128', cat:'quotidien', q:"Qui prend le plus de photos ?", a:["Moi","Toi","Autant les deux","Personne"] },
  { id:'q129', cat:'quotidien', q:"Le meilleur remède à une mauvaise journée ?", a:["Un câlin","Un bon repas","Un verre","Du silence"] },
  { id:'q130', cat:'quotidien', q:"Qui laisse traîner ses chaussures ?", a:["Moi","Toi","Les deux","Personne"] },
  { id:'q131', cat:'quotidien', q:"Notre façon de gérer un budget serré ?", a:["On coupe le superflu","On continue comme avant","On en parle beaucoup","Ça ne nous arrive pas"] },
  { id:'q132', cat:'quotidien', q:"Qui a le plus d'humour ?", a:["Moi","Toi","Autant les deux","Personne ne rit de nos blagues"] },
  { id:'q133', cat:'quotidien', q:"Le petit déjeuner au lit, c'est…", a:["Une habitude","Une occasion rare","Jamais","On aimerait plus souvent"] },
  { id:'q134', cat:'quotidien', q:"Qui met le plus de temps à se préparer ?", a:["Moi","Toi","Autant les deux","On est rapides"] },
  { id:'q135', cat:'quotidien', q:"Notre ambiance sonore préférée à la maison ?", a:["Musique","Télé en fond","Podcast ou radio","Le silence"] },
  { id:'q136', cat:'quotidien', q:"Qui est le plus dépensier ?", a:["Moi","Toi","Autant les deux","Aucun, on économise"] },
  { id:'q137', cat:'quotidien', q:"Le geste du matin qui compte le plus ?", a:["Le bisou avant de partir","Le café préparé","Un message dans la journée","Se lever ensemble"] },
  { id:'q138', cat:'quotidien', q:"Qui est le plus curieux des nouveautés ?", a:["Moi","Toi","Les deux","Aucun, on aime nos habitudes"] },
  { id:'q139', cat:'quotidien', q:"Notre plus grosse différence de caractère ?", a:["Le rythme","La façon de parler","Le rapport au risque","On se ressemble beaucoup"] },
  { id:'q140', cat:'quotidien', q:"Qui pardonne le plus vite ?", a:["Moi","Toi","Autant les deux","Aucun, on rumine"] },
  { id:'q141', cat:'quotidien', q:"Le dîner qu'on partage le plus souvent ?", a:["Devant la télé","À table, en parlant","Chacun à son horaire","Sur le pouce"] },
  { id:'q142', cat:'quotidien', q:"Qui a le plus de projets en tête ?", a:["Moi","Toi","Autant les deux","On vit au jour le jour"] },
  { id:'q143', cat:'quotidien', q:"Notre façon de faire la grasse matinée ?", a:["Vraiment dormir","Discuter au lit","Traîner sur le téléphone","Un câlin puis on se lève"] },
  { id:'q144', cat:'quotidien', q:"Qui remarque une nouvelle coupe de cheveux ?", a:["Moi","Toi","Les deux","Aucun, honnêtement"] },
  { id:'q145', cat:'quotidien', q:"Le truc qu'on ne se lasse jamais de faire ensemble ?", a:["Manger","Marcher","Parler","Ne rien faire"] },
  { id:'q146', cat:'quotidien', q:"Qui est le plus organisé ?", a:["Moi","Toi","Autant les deux","Personne"] },
  { id:'q147', cat:'quotidien', q:"Notre rapport aux tâches du jardin ou du balcon ?", a:["On adore","Un seul s'en occupe","C'est une corvée","On n'en a pas"] },
  { id:'q148', cat:'quotidien', q:"Qui pique la nourriture dans l'assiette de l'autre ?", a:["Moi","Toi","Les deux","Personne, chacun son assiette"] },
  { id:'q149', cat:'quotidien', q:"Le moment de la semaine qu'on préfère ?", a:["Le vendredi soir","Le samedi","Le dimanche midi","Le mercredi"] },
  { id:'q150', cat:'quotidien', q:"Notre plus belle qualité en tant que couple ?", a:["La complicité","La confiance","L'humour","La patience"] },

  // ================= SOUVENIRS & PROJETS =================
  { id:'s001', cat:'souvenir', q:"Notre plus beau souvenir à deux ?", a:["Un voyage","Le jour de notre rencontre","Une fête inoubliable","Un moment tout simple à la maison"] },
  { id:'s002', cat:'souvenir', q:"Ce qui nous a le plus rapprochés ?", a:["Une épreuve traversée ensemble","Un voyage","Le quotidien, jour après jour","Un fou rire mémorable"] },
  { id:'s003', cat:'souvenir', q:"La prochaine folie qu'on devrait faire ?", a:["Partir à l'autre bout du monde","Déménager","Un saut en parachute","Une nuit dans un lieu insolite"] },
  { id:'s004', cat:'souvenir', q:"Notre meilleure destination jusqu'ici ?", a:["La mer","La montagne","Une grande ville","La campagne, au calme"] },
  { id:'s005', cat:'souvenir', q:"Le premier truc qui t'a plu chez l'autre ?", a:["Le sourire","L'humour","Le regard","Le caractère"] },
  { id:'s006', cat:'souvenir', q:"Notre prochain grand projet ?", a:["La maison","Un voyage","La famille","Changer de vie professionnelle"] },
  { id:'s007', cat:'souvenir', q:"Notre chanson, ce serait…", a:["Celle de notre rencontre","Celle qu'on chante en voiture","Une de nos vacances","On n'en a pas vraiment une"] },
  { id:'s008', cat:'souvenir', q:"Le cadeau le plus réussi qu'on se soit fait ?", a:["Un bijou","Un voyage","Un objet fait main","Une surprise organisée"] },
  { id:'s009', cat:'souvenir', q:"Dans 10 ans, on se voit où ?", a:["Une maison à la campagne","Au bord de la mer","À l'étranger","Exactement là où on est"] },
  { id:'s010', cat:'souvenir', q:"Notre pire souvenir de vacances ?", a:["Une galère de transport","Une météo catastrophique","Un logement raté","On n'en a pas eu"] },
  { id:'s011', cat:'souvenir', q:"Ce dont on est le plus fiers ensemble ?", a:["Notre famille","Ce qu'on a construit","D'avoir tenu bon","D'être encore aussi complices"] },
  { id:'s012', cat:'souvenir', q:"Si on refaisait notre première soirée ?", a:["Exactement pareil","Avec plus d'audace","Ailleurs, mais à deux","Plus tôt dans nos vies"] },
  { id:'s013', cat:'souvenir', q:"Notre premier baiser, c'était…", a:["Attendu depuis longtemps","Complètement improvisé","Un peu maladroit","Parfait"] },
  { id:'s014', cat:'souvenir', q:"Qui a fait le premier pas ?", a:["Moi","Toi","Les deux en même temps","Un ami nous a poussés"] },
  { id:'s015', cat:'souvenir', q:"Notre premier voyage ensemble, c'était ?", a:["Un week-end près de chez nous","Une semaine au soleil","Chez de la famille","Un road trip"] },
  { id:'s016', cat:'souvenir', q:"Le moment où on a su que c'était sérieux ?", a:["Très vite","Après quelques mois","En emménageant","On le sait encore mieux aujourd'hui"] },
  { id:'s017', cat:'souvenir', q:"La plus belle surprise reçue de l'autre ?", a:["Un week-end organisé","Un cadeau inattendu","Une déclaration","Un geste du quotidien"] },
  { id:'s018', cat:'souvenir', q:"Notre plus gros fou rire ?", a:["En vacances","Pendant un repas de famille","Au lit","Dans une situation gênante"] },
  { id:'s019', cat:'souvenir', q:"L'endroit qu'on rêve de revoir ensemble ?", a:["Là où on s'est rencontrés","Notre plus beau voyage","La ville de nos débuts","Un endroit jamais visité"] },
  { id:'s020', cat:'souvenir', q:"Notre plus grosse dispute portait sur…", a:["La famille","L'argent","La jalousie","Un truc futile"] },
  { id:'s021', cat:'souvenir', q:"Le déménagement le plus marquant ?", a:["Le premier ensemble","Le plus récent","Celui qui a mal tourné","On n'a pas déménagé"] },
  { id:'s022', cat:'souvenir', q:"La décision la plus courageuse qu'on ait prise ?", a:["Un changement de travail","Un déménagement","Fonder une famille","Se choisir malgré tout"] },
  { id:'s023', cat:'souvenir', q:"Notre meilleur réveillon ?", a:["Entre amis","En famille","Tous les deux","À l'étranger"] },
  { id:'s024', cat:'souvenir', q:"Un rêve commun jamais réalisé ?", a:["Un grand voyage","Une maison particulière","Un projet professionnel","Apprendre quelque chose ensemble"] },
  { id:'s025', cat:'souvenir', q:"Le film qu'on a vu ensemble et qu'on n'oublie pas ?", a:["Un film au cinéma","Un film à la maison","Un film qui nous a fait pleurer","On ne s'en souvient plus"] },
  { id:'s026', cat:'souvenir', q:"Ce qu'on referait exactement pareil ?", a:["Notre rencontre","Notre installation","Nos choix de vie","Tout, sans exception"] },
  { id:'s027', cat:'souvenir', q:"Le plus beau compliment reçu de l'autre ?", a:["Sur mon physique","Sur mon caractère","Sur ce que je fais","Sur ce que je lui apporte"] },
  { id:'s028', cat:'souvenir', q:"Notre première dispute, c'était pour…", a:["Une jalousie","Une histoire de famille","Un malentendu","Je ne m'en souviens pas"] },
  { id:'s029', cat:'souvenir', q:"Le voyage qu'on devrait faire l'an prochain ?", a:["Un pays chaud","Une capitale européenne","La montagne","Un road trip en France"] },
  { id:'s030', cat:'souvenir', q:"Ce qu'on a le mieux réussi ensemble ?", a:["Notre maison","Notre équilibre","Nos enfants ou nos projets","Notre complicité"] },
  { id:'s031', cat:'souvenir', q:"La photo de nous qu'on préfère ?", a:["Une des débuts","Une de vacances","Une de fête","Une prise sur le vif"] },
  { id:'s032', cat:'souvenir', q:"Notre lieu fétiche à deux ?", a:["Un restaurant","Un coin de nature","La maison","Une ville"] },
  { id:'s033', cat:'souvenir', q:"L'objet qu'on garderait s'il ne devait en rester qu'un ?", a:["Une photo","Une lettre","Un bijou","Un souvenir de voyage"] },
  { id:'s034', cat:'souvenir', q:"Le meilleur conseil qu'on nous ait donné ?", a:["Ne jamais se coucher fâchés","Se parler toujours","Garder du temps à deux","On n'écoute pas les conseils"] },
  { id:'s035', cat:'souvenir', q:"Notre plus belle nuit ?", a:["Une nuit de voyage","Une nuit à la maison","Une nuit de fête","Une nuit qu'on n'oubliera pas"] },
  { id:'s036', cat:'souvenir', q:"Si on gagnait au loto, on ferait quoi en premier ?", a:["Une maison","Un tour du monde","On arrête de travailler","On aide nos proches"] },
  { id:'s037', cat:'souvenir', q:"Le pays qu'on rêve de découvrir ensemble ?", a:["Le Japon","L'Italie","Les États-Unis","Une île paradisiaque"] },
  { id:'s038', cat:'souvenir', q:"Ce qui a le plus changé chez nous depuis le début ?", a:["Notre patience","Notre complicité","Notre rythme de vie","Rien, au fond"] },
  { id:'s039', cat:'souvenir', q:"Notre repas le plus mémorable ?", a:["Un grand restaurant","Un repas de famille","Un pique-nique","Un plat raté et un fou rire"] },
  { id:'s040', cat:'souvenir', q:"Le moment où on a eu le plus peur l'un pour l'autre ?", a:["Un problème de santé","Un accident évité","Une séparation possible","Jamais vraiment"] },
  { id:'s041', cat:'souvenir', q:"Ce qu'on veut absolument apprendre à deux ?", a:["Danser","Cuisiner","Une langue","Un sport"] },
  { id:'s042', cat:'souvenir', q:"Notre plus grande fierté de l'année ?", a:["Un projet abouti","Avoir tenu bon","Un voyage","Nos moments à deux"] },
  { id:'s043', cat:'souvenir', q:"Si on écrivait notre histoire, ce serait…", a:["Une comédie romantique","Un road movie","Un drame avec happy end","Une série qui dure"] },
  { id:'s044', cat:'souvenir', q:"L'ami qui a le plus compté dans notre histoire ?", a:["Celui qui nous a présentés","Celui qui nous a soutenus","Un couple ami","Aucun en particulier"] },
  { id:'s045', cat:'souvenir', q:"Notre premier appartement, on s'en souvient comment ?", a:["Petit mais parfait","Une galère","Le meilleur de tous","On n'en a pas eu"] },
  { id:'s046', cat:'souvenir', q:"Ce qu'on aimerait transmettre ?", a:["Le goût du voyage","L'humour","La solidité du couple","La curiosité"] },
  { id:'s047', cat:'souvenir', q:"Le pire cadeau qu'on ait reçu ?", a:["Un objet inutile","Un vêtement horrible","Rien du tout","On a toujours été gâtés"] },
  { id:'s048', cat:'souvenir', q:"Notre soirée la plus arrosée ?", a:["Un mariage","Un nouvel an","Des vacances","On ne se souvient plus, justement"] },
  { id:'s049', cat:'souvenir', q:"Le projet qu'on remet toujours à plus tard ?", a:["Un voyage lointain","Des travaux","Un changement de vie","Se poser vraiment"] },
  { id:'s050', cat:'souvenir', q:"Notre façon de célébrer notre anniversaire de couple ?", a:["Un restaurant","Un week-end","Un cadeau","On oublie souvent"] },
  { id:'s051', cat:'souvenir', q:"Le moment le plus romantique qu'on ait vécu ?", a:["Un coucher de soleil","Une déclaration","Une danse","Un réveil ensemble"] },
  { id:'s052', cat:'souvenir', q:"Ce qui nous a le plus fait grandir ?", a:["Une épreuve","Un déménagement","Un enfant ou un projet","Le temps, simplement"] },
  { id:'s053', cat:'souvenir', q:"La ville où on aimerait vivre un an ?", a:["Une ville du sud","À l'étranger","Une grande capitale","On ne bougerait pas"] },
  { id:'s054', cat:'souvenir', q:"Notre habitude de couple la plus ancienne ?", a:["Un repas rituel","Un surnom","Une sortie régulière","Le câlin du soir"] },
  { id:'s055', cat:'souvenir', q:"Si on pouvait revivre une seule journée ?", a:["Notre rencontre","Un jour de vacances","Un jour de fête","Un jour ordinaire et parfait"] },
  { id:'s056', cat:'souvenir', q:"Le sport ou le loisir qu'on a essayé et abandonné ?", a:["Une salle de sport","La course à pied","Un instrument","Rien, on va au bout"] },
  { id:'s057', cat:'souvenir', q:"Notre plus belle rencontre à deux ?", a:["Un couple d'amis","Quelqu'un en voyage","Un voisin","Personne de marquant"] },
  { id:'s058', cat:'souvenir', q:"Le truc qu'on a construit de nos mains ?", a:["Un meuble","Un aménagement","Un jardin","Rien du tout"] },
  { id:'s059', cat:'souvenir', q:"Notre plus longue séparation ?", a:["Quelques jours","Une semaine","Plusieurs semaines","On ne s'est jamais quittés"] },
  { id:'s060', cat:'souvenir', q:"Ce qu'on a préféré dans nos débuts ?", a:["L'excitation","La découverte de l'autre","La liberté","Les nuits blanches"] },
  { id:'s061', cat:'souvenir', q:"L'anniversaire le plus réussi de l'un de nous ?", a:["Une surprise","Une grande fête","Un voyage","Un moment simple à deux"] },
  { id:'s062', cat:'souvenir', q:"Le prochain endroit à visiter en France ?", a:["La Corse","Les Alpes","La côte atlantique","Paris"] },
  { id:'s063', cat:'souvenir', q:"Ce qui nous a le plus surpris chez l'autre avec le temps ?", a:["Sa patience","Sa force","Sa sensibilité","Son côté joueur"] },
  { id:'s064', cat:'souvenir', q:"Notre pire décision commune ?", a:["Un achat","Un voyage","Un choix de logement","On n'en a pas"] },
  { id:'s065', cat:'souvenir', q:"Le moment de l'année qu'on préfère ensemble ?", a:["Les vacances d'été","Noël","Le printemps","Notre anniversaire de couple"] },
  { id:'s066', cat:'souvenir', q:"Si on devait tout recommencer à zéro ailleurs ?", a:["Je signe tout de suite","Il faudrait me convaincre","Seulement avec un vrai projet","Jamais"] },
  { id:'s067', cat:'souvenir', q:"Notre plus beau cadeau de la vie ?", a:["Nos enfants ou nos proches","Notre rencontre","Notre santé","Notre liberté"] },
  { id:'s068', cat:'souvenir', q:"La tradition qu'on a créée à deux ?", a:["Un repas annuel","Un voyage régulier","Une fête particulière","On n'en a pas"] },
  { id:'s069', cat:'souvenir', q:"Ce qu'on aurait dû faire plus tôt ?", a:["Voyager","S'installer ensemble","Se dire les choses","Prendre du temps à deux"] },
  { id:'s070', cat:'souvenir', q:"Notre meilleur souvenir de fête ?", a:["Un mariage","Un anniversaire","Un festival","Une soirée improvisée"] },
  { id:'s071', cat:'souvenir', q:"Le lieu de notre première nuit ensemble ?", a:["Chez moi","Chez toi","À l'hôtel","Ailleurs, chez des amis"] },
  { id:'s072', cat:'souvenir', q:"Ce qu'on garde de nos familles respectives ?", a:["Les recettes","Les valeurs","Les traditions","Le sens de la fête"] },
  { id:'s073', cat:'souvenir', q:"Notre prochaine étape à deux ?", a:["Un projet immobilier","Un voyage","Un changement de rythme","Continuer comme ça"] },
  { id:'s074', cat:'souvenir', q:"L'objet qui symbolise le mieux notre couple ?", a:["Nos alliances","Une photo","Un meuble","Un souvenir de voyage"] },
  { id:'s075', cat:'souvenir', q:"Le plus beau mot qu'on se soit dit ?", a:["Je t'aime","Merci","Je suis fier de toi","Reste"] },
  { id:'s076', cat:'souvenir', q:"Notre plus belle journée de l'année écoulée ?", a:["Un jour de vacances","Une fête","Un jour ordinaire","Le jour d'une bonne nouvelle"] },
  { id:'s077', cat:'souvenir', q:"Si on avait un an sabbatique ensemble ?", a:["Un tour du monde","Un projet de vie","Du repos","Apprendre autre chose"] },
  { id:'s078', cat:'souvenir', q:"Ce qui nous fait dire qu'on a bien fait de se choisir ?", a:["Les fous rires","Les épreuves surmontées","Le quotidien facile","Tout à la fois"] },
  { id:'s079', cat:'souvenir', q:"Notre pire nuit d'hôtel ?", a:["Bruyante","Sale","Trop chaude ou trop froide","On a toujours bien dormi"] },
  { id:'s080', cat:'souvenir', q:"Le prochain défi qu'on devrait se lancer ?", a:["Un sport ensemble","Un projet créatif","Un voyage difficile","Arrêter une mauvaise habitude"] },
  { id:'s081', cat:'souvenir', q:"Ce qu'on regrette de ne pas avoir photographié ?", a:["Nos débuts","Un voyage","Un moment de fête","Rien, on a tout"] },
  { id:'s082', cat:'souvenir', q:"Notre meilleure décision de l'année ?", a:["Un achat","Un voyage","Un changement d'habitude","Avoir dit non à quelque chose"] },
  { id:'s083', cat:'souvenir', q:"Le souvenir qui nous fait toujours rire ?", a:["Une bêtise en vacances","Une situation gênante","Une chute","Une réplique culte entre nous"] },
  { id:'s084', cat:'souvenir', q:"Si on devait résumer notre couple en un mot ?", a:["Complicité","Solidité","Passion","Douceur"] },
  { id:'s085', cat:'souvenir', q:"Le voyage qu'on n'aurait pas dû faire ?", a:["Trop cher","Mauvaise période","Mauvaise compagnie","Aucun, tous étaient bien"] },
  { id:'s086', cat:'souvenir', q:"Notre plus grande peur pour l'avenir ?", a:["La santé","L'argent","La routine","Aucune, on est confiants"] },
  { id:'s087', cat:'souvenir', q:"Ce qu'on veut absolument faire avant 60 ans ?", a:["Un grand voyage","Une maison de rêve","Un projet fou","Profiter, simplement"] },
  { id:'s088', cat:'souvenir', q:"Le premier repas qu'on a partagé ?", a:["Au restaurant","À la maison","Sur le pouce","Je ne m'en souviens pas"] },
  { id:'s089', cat:'souvenir', q:"Notre rituel de retrouvailles après une absence ?", a:["Un long câlin","Un bon repas","Tout se raconter","Aller directement au lit"] },
  { id:'s090', cat:'souvenir', q:"Ce qui rend notre couple différent des autres ?", a:["Notre humour","Notre liberté","Notre façon de communiquer","Rien, on est un couple normal"] },
  { id:'s091', cat:'souvenir', q:"Le moment où on s'est senti le plus fier de l'autre ?", a:["Une réussite professionnelle","Un moment de courage","Face à la famille","Au quotidien, souvent"] },
  { id:'s092', cat:'souvenir', q:"Notre plus belle balade ?", a:["En bord de mer","En forêt","En montagne","Dans une ville la nuit"] },
  { id:'s093', cat:'souvenir', q:"Si on pouvait effacer un souvenir ?", a:["Une dispute","Une trahison","Une période difficile","Aucun, tout compte"] },
  { id:'s094', cat:'souvenir', q:"Le meilleur moment d'un voyage pour nous ?", a:["Le départ","L'arrivée","Les imprévus","Le retour à la maison"] },
  { id:'s095', cat:'souvenir', q:"Notre projet secret à deux ?", a:["Un voyage","Un achat","Un changement de vie","On n'a pas de secret"] },
  { id:'s096', cat:'souvenir', q:"Ce qu'on aime raconter aux autres sur nous ?", a:["Notre rencontre","Nos voyages","Nos bêtises","Rien, on est discrets"] },
  { id:'s097', cat:'souvenir', q:"Le cadeau qu'on rêve de recevoir de l'autre ?", a:["Un voyage surprise","Un bijou","Du temps ensemble","Une lettre"] },
  { id:'s098', cat:'souvenir', q:"Notre meilleur souvenir de l'hiver dernier ?", a:["Une soirée au chaud","Un week-end","Les fêtes","Rien de particulier"] },
  { id:'s099', cat:'souvenir', q:"Ce qui nous manquerait le plus si l'autre partait un mois ?", a:["Sa présence le soir","Les repas partagés","Les câlins","Les discussions"] },
  { id:'s100', cat:'souvenir', q:"Notre histoire, dans dix ans, on la verra comment ?", a:["Encore plus forte","Plus tranquille","Pleine de nouveaux projets","Exactement pareil"] },

  // ================= INTIMITÉ DU COUPLE =================
  // Volontairement explicites : une réponse commune sur ces sujets dit
  // quelque chose, une allusion ne dit rien.
  { id:'c001', cat:'coquin', q:"La position qu'on refait le plus souvent ?", a:["Le missionnaire","La levrette","À califourchon","La cuillère"] },
  { id:'c002', cat:'coquin', q:"Le sexe oral, pour toi, c'est…", a:["Indispensable à chaque fois","Un préliminaire parmi d'autres","Un plaisir à part entière","Occasionnel"] },
  { id:'c003', cat:'coquin', q:"Notre rythme idéal par semaine ?", a:["1 à 2 fois","3 à 4 fois","5 fois et plus","Tous les jours"] },
  { id:'c004', cat:'coquin', q:"Qui atteint l'orgasme le plus vite ?", a:["Moi","Toi","À peu près en même temps","Ça dépend des soirs"] },
  { id:'c005', cat:'coquin', q:"Tu préfères quand c'est…", a:["Doux et lent","Rapide et intense","Long et joueur","Ça dépend de l'humeur"] },
  { id:'c006', cat:'coquin', q:"Ce qui te ferait craquer sur-le-champ ?", a:["Une fellation surprise","Un strip-tease","Des mots crus à l'oreille","Être attaché·e"] },
  { id:'c007', cat:'coquin', q:"L'endroit du corps où tu préfères être embrassé·e ?", a:["Le cou","L'intérieur des cuisses","Le bas du ventre","Les lèvres"] },
  { id:'c008', cat:'coquin', q:"La pratique jamais faite qui te tente le plus ?", a:["La sodomie","Un jeu de domination","L'exhibition","Se filmer"] },
  { id:'c009', cat:'coquin', q:"Où on devrait le faire ce week-end ?", a:["Sous la douche","Sur la table de la cuisine","Dans la voiture","Dehors, à la nuit tombée"] },
  { id:'c010', cat:'coquin', q:"Le sextoy qu'on devrait s'offrir ?", a:["Un vibromasseur","Un plug","Un anneau","Aucun, on n'en a pas besoin"] },
  { id:'c011', cat:'coquin', q:"Qui devrait prendre le contrôle plus souvent ?", a:["Moi","Toi","Chacun son tour","On est déjà équilibrés"] },
  { id:'c012', cat:'coquin', q:"Le meilleur moment pour un rapport express ?", a:["Le matin avant le travail","L'après-midi, en douce","En rentrant le soir","En pleine nuit"] },
  { id:'c013', cat:'coquin', q:"Ce qui manque le plus à notre vie sexuelle ?", a:["La fréquence","La spontanéité","L'audace","Rien, elle me va très bien"] },
  { id:'c014', cat:'coquin', q:"Nos meilleurs ébats, c'était plutôt…", a:["Un matin au réveil","Un après-midi volé","Une nuit entière","Un rapport pressé et brûlant"] },
  { id:'c015', cat:'coquin', q:"Le fantasme le plus réaliste à réaliser cette année ?", a:["Un jeu de rôle","Une nuit à l'hôtel","Se filmer","Un club libertin"] },
  { id:'c016', cat:'coquin', q:"Pendant l'amour, tu aimes…", a:["Le silence","Parler cru","Les gémissements","De la musique en fond"] },
  { id:'c017', cat:'coquin', q:"Ce qui te met le plus en condition dans la journée ?", a:["Un message très explicite","Une photo osée","Un geste discret en public","Ne rien savoir et être surpris·e"] },
  { id:'c018', cat:'coquin', q:"On devrait finir plus souvent…", a:["En même temps","Chacun son tour","Peu importe, c'est le trajet qui compte","Deux fois plutôt qu'une"] },
  { id:'c019', cat:'coquin', q:"La durée idéale d'un rapport ?", a:["Moins de 10 minutes","Entre 10 et 30 minutes","Plus de 30 minutes","Toute une soirée"] },
  { id:'c020', cat:'coquin', q:"Qui initie le plus souvent ?", a:["Moi","Toi","Autant les deux","Personne, il faudrait s'y remettre"] },
  { id:'c021', cat:'coquin', q:"Les préliminaires, tu les veux…", a:["Très longs","Courts, on va à l'essentiel","Variables selon l'envie","Ce sont eux le meilleur moment"] },
  { id:'c022', cat:'coquin', q:"Lumière allumée ou éteinte ?", a:["Allumée","Éteinte","Tamisée","Peu importe"] },
  { id:'c023', cat:'coquin', q:"Ce que tu préfères recevoir ?", a:["Un cunnilingus ou une fellation","Un massage qui dérape","Une pénétration lente","Des caresses partout"] },
  { id:'c024', cat:'coquin', q:"Le lieu le plus excitant qu'on ait testé ?", a:["La douche","La voiture","Dehors","On n'est jamais sortis du lit"] },
  { id:'c025', cat:'coquin', q:"Un accessoire à essayer en premier ?", a:["Un bandeau sur les yeux","Des menottes","Une plume ou un fouet léger","Une huile chauffante"] },
  { id:'c026', cat:'coquin', q:"Le matin, tu es plutôt…", a:["Toujours partant·e","Seulement le week-end","Jamais avant le café","Ça dépend du réveil"] },
  { id:'c027', cat:'coquin', q:"Les sous-vêtements de l'autre, tu les veux…", a:["En dentelle","Simples et confortables","Un ensemble assorti","Aucun"] },
  { id:'c028', cat:'coquin', q:"Ce qui coupe le plus l'envie ?", a:["La fatigue","Le stress","Une dispute","Les enfants ou le bruit"] },
  { id:'c029', cat:'coquin', q:"Un rapport après une dispute, c'est…", a:["Le meilleur","Impossible pour moi","Ça arrive","On préfère régler d'abord"] },
  { id:'c030', cat:'coquin', q:"Tu préfères être…", a:["Dominant·e","Dominé·e","Les deux selon l'envie","Ni l'un ni l'autre"] },
  { id:'c031', cat:'coquin', q:"Le meilleur endroit pour un massage qui dégénère ?", a:["Le dos","Les fesses","Les cuisses","Les pieds"] },
  { id:'c032', cat:'coquin', q:"On devrait mettre plus de…", a:["Jeux et défis","Lingerie","Sextoys","Spontanéité"] },
  { id:'c033', cat:'coquin', q:"Faire l'amour avec un miroir en face ?", a:["Très excitant","Un peu gênant","À tester","Non merci"] },
  { id:'c034', cat:'coquin', q:"Le meilleur moment de la semaine pour nous ?", a:["Le vendredi soir","Le samedi matin","Le dimanche après-midi","N'importe quand"] },
  { id:'c035', cat:'coquin', q:"Se caresser devant l'autre, c'est…", a:["Très excitant","Intimidant","Quelque chose qu'on fait déjà","Jamais essayé"] },
  { id:'c036', cat:'coquin', q:"Ce qui te fait le plus d'effet chez l'autre, physiquement ?", a:["Le regard","Les fesses","La poitrine ou le torse","Les mains"] },
  { id:'c037', cat:'coquin', q:"Un week-end entièrement dédié au sexe ?", a:["Oui, dès demain","Oui mais avec des pauses","Une journée suffirait","Non, ça deviendrait mécanique"] },
  { id:'c038', cat:'coquin', q:"Les mots pendant l'amour, tu les veux…", a:["Très crus","Tendres","Un mélange","Le moins possible"] },
  { id:'c039', cat:'coquin', q:"La tenue qui te fait le plus craquer ?", a:["De la lingerie fine","Une chemise ouverte","Un simple t-shirt","Rien du tout"] },
  { id:'c040', cat:'coquin', q:"Faire l'amour ailleurs qu'à la maison ?", a:["Indispensable de temps en temps","Sympa mais rare","Trop risqué","On le fait déjà souvent"] },
  { id:'c041', cat:'coquin', q:"Ce qui t'excite le plus dans les préliminaires ?", a:["L'attente","Les caresses","Le sexe oral","Se déshabiller mutuellement"] },
  { id:'c042', cat:'coquin', q:"Un jeu de rôle, ce serait plutôt…", a:["Patron et employé·e","Inconnus dans un bar","Massage professionnel","Aucun, ça me gêne"] },
  { id:'c043', cat:'coquin', q:"On devrait faire l'amour plus souvent…", a:["Le matin","L'après-midi","Le soir","La nuit"] },
  { id:'c044', cat:'coquin', q:"Après l'amour, tu préfères…", a:["Un câlin","Parler","Dormir tout de suite","Recommencer"] },
  { id:'c045', cat:'coquin', q:"Regarder un film pour adultes ensemble ?", a:["On l'a déjà fait et j'aime","Ça m'intéresse","Ça ne m'attire pas","Seulement chacun de son côté"] },
  { id:'c046', cat:'coquin', q:"Ce qui rendrait notre vie sexuelle parfaite ?", a:["Plus de temps","Plus d'audace","Plus de fréquence","Elle l'est déjà"] },
  { id:'c047', cat:'coquin', q:"La position qu'on devrait retenter ?", a:["Celle qu'on a abandonnée","Une nouvelle","Toujours la même, elle marche","Celle qui nous a fait rire"] },
  { id:'c048', cat:'coquin', q:"Tu aimes qu'on te touche surtout…", a:["Avec les mains","Avec la bouche","Avec tout le corps","Avec un accessoire"] },
  { id:'c049', cat:'coquin', q:"L'idée d'un club échangiste ?", a:["Ça m'attire vraiment","Curieux mais sans passer à l'acte","Absolument pas","À en parler sérieusement"] },
  { id:'c050', cat:'coquin', q:"Le meilleur aphrodisiaque pour nous ?", a:["Un verre de vin","Une soirée sans enfants","Un massage","Une dispute réglée"] },
  { id:'c051', cat:'coquin', q:"Se faire attendre toute la journée, ça te…", a:["Rend fou de désir","Agace un peu","Fait oublier","Donne envie de doubler la mise"] },
  { id:'c052', cat:'coquin', q:"On s'embrasse assez pendant l'amour ?", a:["Oui, tout le temps","Pas assez","Ça dépend des positions","On préfère autre chose"] },
  { id:'c053', cat:'coquin', q:"Le bruit, chez toi, c'est…", a:["Assumé et fort","Discret","Retenu à cause des autres","Silencieux"] },
  { id:'c054', cat:'coquin', q:"Faire l'amour dans le noir complet ?", a:["J'adore","Ça me met mal à l'aise","Indifférent","Seulement parfois"] },
  { id:'c055', cat:'coquin', q:"Un strip-tease de l'autre, tu le veux…", a:["Lent et appliqué","Drôle et improvisé","En musique","Pas du tout"] },
  { id:'c056', cat:'coquin', q:"Le nombre de fois où on l'a fait ce mois-ci ?", a:["Moins de 3","Entre 3 et 6","Entre 7 et 12","Plus de 12"] },
  { id:'c057', cat:'coquin', q:"Ce que tu n'oses pas demander ?", a:["Une pratique précise","Plus de fréquence","Plus de douceur","Rien, je demande tout"] },
  { id:'c058', cat:'coquin', q:"L'endroit de la maison jamais utilisé ?", a:["La cuisine","Le canapé","La douche","Il n'en reste aucun"] },
  { id:'c059', cat:'coquin', q:"Tu préfères un rapport…", a:["Prévu et attendu","Complètement imprévu","Après une soirée","Au réveil"] },
  { id:'c060', cat:'coquin', q:"Les mains attachées, ça te…", a:["Excite beaucoup","Inquiète un peu","Laisse indifférent","Donne envie d'essayer"] },
  { id:'c061', cat:'coquin', q:"Ce qui te plaît le plus dans le corps de l'autre au réveil ?", a:["Son visage","Sa nudité","Sa chaleur","Ses cheveux en bataille"] },
  { id:'c062', cat:'coquin', q:"Un sexto en pleine réunion ?", a:["J'adore en recevoir","J'adore en envoyer","Les deux","Trop risqué"] },
  { id:'c063', cat:'coquin', q:"Notre meilleur souvenir intime, c'était…", a:["En vacances","Un soir ordinaire","Après une longue absence","Au tout début"] },
  { id:'c064', cat:'coquin', q:"Tu aimes qu'on te déshabille ou tu préfères le faire ?", a:["Qu'on me déshabille","Le faire moi-même","Se déshabiller mutuellement","Peu importe, vite"] },
  { id:'c065', cat:'coquin', q:"L'huile de massage, chez nous…", a:["On l'utilise souvent","On en a mais jamais","À acheter d'urgence","Ça ne m'attire pas"] },
  { id:'c066', cat:'coquin', q:"Ce qui t'excite le plus mentalement ?", a:["Le désir de l'autre","L'interdit","La tendresse","La surprise"] },
  { id:'c067', cat:'coquin', q:"Faire l'amour en extérieur ?", a:["Déjà fait, à refaire","Jamais fait, ça me tente","Trop peur d'être vus","Ça ne m'intéresse pas"] },
  { id:'c068', cat:'coquin', q:"Le rythme que tu préfères ?", a:["Lent du début à la fin","Crescendo","Alterné","Rapide tout de suite"] },
  { id:'c069', cat:'coquin', q:"Une nuit d'hôtel juste pour ça ?", a:["Dès ce week-end","Une fois par an","Pas nécessaire","On devrait en faire une tradition"] },
  { id:'c070', cat:'coquin', q:"Ce qui te ferait le plus plaisir ce soir ?", a:["Un massage complet","Un rapport passionné","Une longue séance de préliminaires","Juste un câlin"] },
  { id:'c071', cat:'coquin', q:"Tu penses à quoi pendant ?", a:["À l'autre uniquement","À des images ou des fantasmes","À rien du tout","Ça dépend des moments"] },
  { id:'c072', cat:'coquin', q:"Ce qu'on devrait arrêter de faire ?", a:["Attendre le soir","Repousser par fatigue","Faire toujours pareil","Rien, tout va bien"] },
  { id:'c073', cat:'coquin', q:"L'orgasme le plus intense, tu le dois à…", a:["La pénétration","Le sexe oral","Les mains","Un accessoire"] },
  { id:'c074', cat:'coquin', q:"La température idéale de la pièce ?", a:["Bien chaude","Fraîche","Peu importe","Sous la couette de toute façon"] },
  { id:'c075', cat:'coquin', q:"Un compliment sur ton corps te fait…", a:["Beaucoup d'effet","Un peu rougir","Douter","Envie d'en entendre plus"] },
  { id:'c076', cat:'coquin', q:"Ce qui te manque le plus quand on est séparés ?", a:["Le sexe","Les câlins","Dormir collés","Les baisers"] },
  { id:'c077', cat:'coquin', q:"On parle assez de sexe entre nous ?", a:["Oui, librement","Pas assez","Seulement au lit","Presque jamais"] },
  { id:'c078', cat:'coquin', q:"Ta zone érogène la plus méconnue ?", a:["La nuque","Le creux des reins","L'intérieur des poignets","Derrière les genoux"] },
  { id:'c079', cat:'coquin', q:"Se réveiller par une caresse intime ?", a:["Le meilleur des réveils","Seulement le week-end","Ça me réveille mal","À faire plus souvent"] },
  { id:'c080', cat:'coquin', q:"Un rapport dans la journée, sans prévenir ?", a:["Idéal","Il faut que je sois disponible","Rare mais délicieux","Impossible chez nous"] },
  { id:'c081', cat:'coquin', q:"Ce qu'on ne fait pas assez ?", a:["Les préliminaires","Les nouveautés","Se le dire","S'isoler vraiment"] },
  { id:'c082', cat:'coquin', q:"Les fesses, dans notre couple, c'est…", a:["Un terrain de jeu","Une zone tendre","Un sujet à explorer","Pas un sujet"] },
  { id:'c083', cat:'coquin', q:"Tu préfères prendre ou donner du plaisir ?", a:["Donner","Recevoir","Les deux à égalité","Alterner dans la même soirée"] },
  { id:'c084', cat:'coquin', q:"Le vibromasseur pendant l'acte ?", a:["Excellent","À tester","Ça me dérange","On le fait déjà"] },
  { id:'c085', cat:'coquin', q:"Ce qu'on devrait s'interdire un soir pour pimenter ?", a:["La pénétration","Les mains","De parler","De se voir, dans le noir"] },
  { id:'c086', cat:'coquin', q:"Le désir, chez toi, vient plutôt…", a:["D'un coup, spontanément","En cours de route","Après un moment de tendresse","Quand l'autre insiste un peu"] },
  { id:'c087', cat:'coquin', q:"Une photo osée envoyée dans la journée ?", a:["J'adore recevoir","J'adore envoyer","Les deux","Jamais, trop risqué"] },
  { id:'c088', cat:'coquin', q:"Notre plus grosse différence au lit ?", a:["Le rythme","La fréquence souhaitée","L'audace","Aucune, on est raccord"] },
  { id:'c089', cat:'coquin', q:"Faire l'amour habillés, à moitié ?", a:["Très excitant","On l'a fait, c'était bien","Jamais essayé","Je préfère nu"] },
  { id:'c090', cat:'coquin', q:"Le meilleur endroit du corps pour une morsure douce ?", a:["L'épaule","Le cou","La lèvre","Les fesses"] },
  { id:'c091', cat:'coquin', q:"Un scénario où l'un dirige tout ?", a:["Je veux diriger","Je veux être dirigé·e","Chacun son soir","Ça ne me tente pas"] },
  { id:'c092', cat:'coquin', q:"On devrait programmer nos moments intimes ?", a:["Oui, sinon ça n'arrive pas","Non, ça tue le désir","Un compromis","On le fait déjà sans le dire"] },
  { id:'c093', cat:'coquin', q:"La chose qui te fait le plus rire au lit ?", a:["Les bruits involontaires","Les positions ratées","Les crampes","Rien, je reste concentré·e"] },
  { id:'c094', cat:'coquin', q:"Après combien de temps sans, tu deviens grognon ?", a:["2 jours","Une semaine","Deux semaines","Un mois"] },
  { id:'c095', cat:'coquin', q:"Un petit mot cru murmuré, ça te…", a:["Excite immédiatement","Fait sourire","Gêne","Donne envie de répondre"] },
  { id:'c096', cat:'coquin', q:"Ce qu'on devrait acheter pour la chambre ?", a:["De la lingerie","Des accessoires","Un éclairage tamisé","Une meilleure literie"] },
  { id:'c097', cat:'coquin', q:"L'idée d'être surpris par quelqu'un ?", a:["Terrifiante","Un peu excitante","Très excitante","Ça ne changerait rien"] },
  { id:'c098', cat:'coquin', q:"Notre code secret pour dire « ce soir » ?", a:["Un mot précis","Un regard","Un geste","On n'en a pas"] },
  { id:'c099', cat:'coquin', q:"Tu préfères une longue séance ou plusieurs courtes ?", a:["Une longue","Plusieurs courtes","Les deux dans la semaine","Une longue par mois suffit"] },
  { id:'c100', cat:'coquin', q:"Le plus excitant dans un lieu public ?", a:["Le risque","L'interdit","La rapidité","Rien, ça m'angoisse"] },
  { id:'c101', cat:'coquin', q:"Se doucher ensemble mène toujours à…", a:["Un rapport","Des caresses","Rien, on se lave","Un fou rire"] },
  { id:'c102', cat:'coquin', q:"Ton fantasme le plus récurrent implique…", a:["Un lieu inhabituel","Une contrainte ou un jeu de pouvoir","Une troisième personne","Juste nous, mais autrement"] },
  { id:'c103', cat:'coquin', q:"Le meilleur signal que l'autre a envie ?", a:["Un regard appuyé","Une main baladeuse","Une tenue choisie","Il le dit clairement"] },
  { id:'c104', cat:'coquin', q:"Ce que tu changerais dans notre routine intime ?", a:["Le moment de la journée","Le lieu","La durée","Rien du tout"] },
  { id:'c105', cat:'coquin', q:"Un bandeau sur les yeux, ça change…", a:["Tout, en mieux","Un peu","Ça me stresse","Jamais essayé"] },
  { id:'c106', cat:'coquin', q:"Le plus important pour toi ?", a:["L'orgasme","La connexion","La performance","La tendresse après"] },
  { id:'c107', cat:'coquin', q:"On a déjà fait l'amour dans une voiture ?", a:["Oui, plusieurs fois","Une fois","Jamais, ça me tente","Jamais, et ça ne me tente pas"] },
  { id:'c108', cat:'coquin', q:"Ce qui te ferait dire oui immédiatement ce soir ?", a:["Un massage","Un verre","Un message coquin","Rien à négocier, je suis partant·e"] },
  { id:'c109', cat:'coquin', q:"Le sexe le matin, c'est…", a:["Le meilleur","Compliqué avec l'haleine","Trop pressé","À instaurer le week-end"] },
  { id:'c110', cat:'coquin', q:"Tu préfères qu'on garde…", a:["Les chaussettes","Un haut","Un bijou","Rien du tout"] },
  { id:'c111', cat:'coquin', q:"L'intensité idéale ?", a:["Douce et sensuelle","Passionnée","Brutale parfois","Ça dépend de la semaine"] },
  { id:'c112', cat:'coquin', q:"Notre meilleure position pour l'orgasme féminin ?", a:["À califourchon","La levrette","Le missionnaire avec les jambes relevées","Pas de pénétration"] },
  { id:'c113', cat:'coquin', q:"Se raconter un fantasme à voix haute ?", a:["On l'a fait, c'était fort","J'aimerais essayer","Je n'oserais pas","Ça ne m'intéresse pas"] },
  { id:'c114', cat:'coquin', q:"Le plus frustrant pour toi ?", a:["Être interrompu","La fatigue de l'autre","Un rapport trop court","Ne pas oser demander"] },
  { id:'c115', cat:'coquin', q:"Un rapport uniquement pour le plaisir de l'autre ?", a:["Je le fais souvent","J'aimerais qu'on le fasse","Ça n'a pas de sens pour moi","On le fait chacun son tour"] },
  { id:'c116', cat:'coquin', q:"Le meilleur endroit pour commencer un massage ?", a:["Les épaules","Le bas du dos","Les cuisses","La nuque"] },
  { id:'c117', cat:'coquin', q:"Ce qu'on devrait tester dans le noir total ?", a:["Un jeu de devinettes","Se caresser sans parler","Un accessoire","Rien de spécial"] },
  { id:'c118', cat:'coquin', q:"L'après, chez nous, c'est plutôt…", a:["Long et câlin","Court, on s'endort","Une douche","On repart pour un tour"] },
  { id:'c119', cat:'coquin', q:"Tu aimerais qu'on soit plus…", a:["Bruyants","Lents","Joueurs","Spontanés"] },
  { id:'c120', cat:'coquin', q:"Le jour de la semaine où on a le plus envie ?", a:["Le vendredi","Le samedi","Le dimanche","N'importe lequel"] },
  { id:'c121', cat:'coquin', q:"Un rapport après une soirée arrosée ?", a:["Toujours meilleur","Toujours raté","Ça dépend de la quantité","On s'endort avant"] },
  { id:'c122', cat:'coquin', q:"Ce que tu aimes voir chez l'autre pendant ?", a:["Son visage","Ses mains","Tout son corps","Ses yeux fermés"] },
  { id:'c123', cat:'coquin', q:"Les jeux de pouvoir, chez nous ?", a:["On en fait déjà","J'aimerais essayer","Ça ne me parle pas","Seulement en douceur"] },
  { id:'c124', cat:'coquin', q:"On devrait se filmer une fois ?", a:["Oui, et le garder","Oui, et l'effacer après","Non, trop risqué","Ça ne m'attire pas"] },
  { id:'c125', cat:'coquin', q:"La lingerie, c'est surtout pour…", a:["L'autre","Moi","Les deux","Rien, ça finit par terre"] },
  { id:'c126', cat:'coquin', q:"Ce qui te ferait rougir devant l'autre ?", a:["Me caresser devant lui","Dire un fantasme","Un déguisement","Rien, je n'ai plus de pudeur"] },
  { id:'c127', cat:'coquin', q:"Le baiser pendant l'amour, tu le veux…", a:["Constant","Au début seulement","À la fin","Il me distrait"] },
  { id:'c128', cat:'coquin', q:"Notre plus grand tabou ?", a:["Un sujet dont on ne parle pas","Une pratique refusée","Nos ex","On n'a aucun tabou"] },
  { id:'c129', cat:'coquin', q:"Un soir sans enfants ni obligations, on ferait quoi ?", a:["L'amour toute la soirée","Un dîner puis l'amour","Un film puis l'amour","On dormirait, enfin"] },
  { id:'c130', cat:'coquin', q:"Le plaisir solitaire, dans notre couple ?", a:["On en parle librement","Chacun de son côté, en silence","Ensemble, parfois","Sujet jamais abordé"] },
  { id:'c131', cat:'coquin', q:"Ce que tu veux entendre juste avant ?", a:["J'ai envie de toi","Tu es magnifique","Un mot très cru","Rien, les gestes suffisent"] },
  { id:'c132', cat:'coquin', q:"La position la plus surestimée ?", a:["La levrette","La brouette","Debout","Aucune, toutes ont leur intérêt"] },
  { id:'c133', cat:'coquin', q:"On devrait refaire l'amour là où on l'a fait la première fois ?", a:["Oui, absolument","Ce serait bizarre","C'est impossible aujourd'hui","On l'a déjà refait"] },
  { id:'c134', cat:'coquin', q:"Ton moment préféré d'un rapport ?", a:["Le tout début","La montée","L'orgasme","Les minutes qui suivent"] },
  { id:'c135', cat:'coquin', q:"Un accessoire porté toute la soirée en secret ?", a:["Très excitant","Amusant","Inconfortable","Jamais de la vie"] },
  { id:'c136', cat:'coquin', q:"Ce qui rend un rapport inoubliable ?", a:["L'intensité","Le lieu","La surprise","L'émotion"] },
  { id:'c137', cat:'coquin', q:"On se complimente assez physiquement ?", a:["Oui, souvent","Pas assez","Seulement au lit","Presque jamais"] },
  { id:'c138', cat:'coquin', q:"Le meilleur cadeau coquin à offrir ?", a:["De la lingerie","Un accessoire","Un bon pour un massage","Une nuit d'hôtel"] },
  { id:'c139', cat:'coquin', q:"Tu préfères l'initiative ou l'invitation ?", a:["Prendre l'initiative","Être invité·e","Les deux","Que ça vienne naturellement"] },
  { id:'c140', cat:'coquin', q:"Ce qui te fait le plus d'effet dans un baiser ?", a:["La langue","Les mains dans les cheveux","La lenteur","La surprise"] },
  { id:'c141', cat:'coquin', q:"Une soirée entière de préliminaires sans aller plus loin ?", a:["Torture délicieuse","Frustrant","Excellente idée","Impossible pour moi"] },
  { id:'c142', cat:'coquin', q:"Le plus grand frein chez nous ?", a:["Le manque de temps","La fatigue","Les enfants","La routine"] },
  { id:'c143', cat:'coquin', q:"Tu aimes qu'on te regarde te déshabiller ?", a:["Beaucoup","Un peu gênant","Pas du tout","Seulement dans la pénombre"] },
  { id:'c144', cat:'coquin', q:"Notre pratique commune préférée ?", a:["Le sexe oral","La pénétration","Les caresses","Les jeux"] },
  { id:'c145', cat:'coquin', q:"Ce qu'on devrait s'autoriser une fois par mois ?", a:["Une nuit d'hôtel","Un jeu nouveau","Une soirée sans téléphone","Un rapport en plein jour"] },
  { id:'c146', cat:'coquin', q:"Le silence complet pendant l'amour ?", a:["Très intense","Trop bizarre","On le fait déjà","À essayer"] },
  { id:'c147', cat:'coquin', q:"Ce qui te ferait le plus plaisir qu'on te dise après ?", a:["C'était incroyable","Je t'aime","Recommençons","Rien, un câlin suffit"] },
  { id:'c148', cat:'coquin', q:"Notre rapport le plus mémorable a eu lieu…", a:["Cette année","Il y a quelques années","Au tout début","Il reste à venir"] },
  { id:'c149', cat:'coquin', q:"Si on devait choisir une seule pratique à vie ?", a:["Le sexe oral","La pénétration classique","Les mains","Les jeux et accessoires"] },
  { id:'c150', cat:'coquin', q:"Sur dix, tu notes notre vie sexuelle…", a:["Entre 5 et 6","7 ou 8","9 ou 10","Moins de 5, il faut agir"] }
];
