// Banque de cartes par défaut. category: 'question' | 'defi' | 'gage'
// Chaque carte a un id stable ("d0", "d1"...) pour pouvoir être masquée/éditée depuis l'appli.
const DEFAULT_CARDS_RAW = [
  // QUESTIONS (découverte / complicité)
  { cat:'question', text:"Quel est le souvenir le plus exceptionnel que tu ai aprécié depuis que l'on est ensemble ?", pts:10 },
  { cat:'question', text:"Si on pouvait revivre une seule de nos journées ensemble, laquelle choisirais-tu ?", pts:10 },
  { cat:'question', text:"Quelle qualité chez moi t'a fait craquer au tout début ?", pts:10 },
  { cat:'question', text:"Quel est le rêve qu'on n'a pas encore réalisé ensemble ?", pts:15 },
  { cat:'question', text:"Décris-moi en trois mots, sans réfléchir.", pts:5 },
  { cat:'question', text:"Quelle habitude de moi te fait sourire en cachette ?", pts:10 },
  { cat:'question', text:"Où aimerais-tu qu'on soit dans 5 ans ?", pts:15 },
  { cat:'question', text:"Quel petit geste du quotidien te fait te sentir aimé(e) ?", pts:10 },
  { cat:'question', text:"Raconte-moi un moment où tu as été fier/fière de moi.", pts:10 },
  { cat:'question', text:"Si on partait demain en voyage surprise, où voudrais-tu aller ?", pts:10 },
  { cat:'question', text:"Quelle chanson te fait penser à nous ?", pts:5 },
  { cat:'question', text:"Quel est ton souvenir préféré de notre rencontre ?", pts:10 },

  // DÉFIS (action, complicité physique ou créative)
  { cat:'defi', text:"Improvise une danse de 20 secondes sur la première chanson qui passe.", pts:15 },
  { cat:'defi', text:"Fais-moi un compliment sincère sans utiliser le mot 'beau/belle'.", pts:10 },
  { cat:'defi', text:"Imite la façon dont je parle quand je suis fatigué(e).", pts:15 },
  { cat:'defi', text:"Prends une photo improvisée de nous deux, la plus drôle possible.", pts:10 },
  { cat:'defi', text:"Raconte une blague — si je ne ris pas, tu perds les points.", pts:10 },
  { cat:'defi', text:"Fais-moi un massage des épaules pendant 2 minutes.", pts:15 },
  { cat:'defi', text:"Écris un petit mot doux que je garderai dans mon portefeuille.", pts:15 },
  { cat:'defi', text:"Devine ce à quoi je pense en ce moment, en 3 essais.", pts:10 },
  { cat:'defi', text:"Prépare-moi une boisson surprise avec ce qu'on a dans les placards.", pts:15 },
  { cat:'defi', text:"Chante les 10 premières secondes de notre chanson préférée.", pts:10 },

  // GAGES (espiègles, légers)
  { cat:'gage', text:"Tu dois parler avec un accent au choix de l'autre pendant 10 minutes.", pts:15 },
  { cat:'gage', text:"Laisse l'autre choisir ta tenue pour demain.", pts:10 },
  { cat:'gage', text:"Fais 15 pompes ou squats, au choix du/de la partenaire.", pts:10 },
  { cat:'gage', text:"Envoie un message doux à ton/ta partenaire en plein milieu d'une activité du quotidien (sans prévenir).", pts:15 },
  { cat:'gage', text:"Tu dois répondre 'oui mon cœur' à tout pendant 30 minutes.", pts:15 },
  { cat:'gage', text:"Laisse l'autre publier une story à ta place (gentille, promis).", pts:10 },
  { cat:'gage', text:"Pas de téléphone pendant 1 heure, juste vous deux.", pts:20 },
  { cat:'gage', text:"Tu dois faire un compliment à voix haute à chaque pièce où tu entres ce soir.", pts:10 },

  // SURPRISE (mélange aléatoire de tout, points plus variables)
  { cat:'surprise', text:"Tirage mystère : l'autre choisit pour toi entre une question, un défi ou un gage.", pts:20 },
  { cat:'surprise', text:"Organise un mini rendez-vous improvisé dans les 48h qui suivent.", pts:25 },
  { cat:'surprise', text:"Offre un massage de 5 minutes sans qu'on te le demande deux fois.", pts:15 },
  { cat:'surprise', text:"Prépare le petit-déjeuner ou le dîner surprise de l'autre, sans lui dire.", pts:20 },

  // CONTENU SENSUEL (mêlé aux catégories existantes — pour pimenter la soirée)
  { cat:'question', text:"Quel est ton fantasme que tu n'as encore jamais osé me dire ?", pts:20 },
  { cat:'question', text:"Quelle partie de mon corps préfères-tu, et pourquoi ?", pts:15 },
  { cat:'question', text:"Décris le moment où tu m'as désiré(e) le plus fort.", pts:15 },
  { cat:'question', text:"Qu'est-ce que tu aimerais qu'on essaie ensemble, qu'on n'a jamais fait ?", pts:20 },
  { cat:'question', text:"Sur une échelle de 1 à 10, à quel point as-tu envie de moi là, maintenant ?", pts:10 },

  { cat:'defi', text:"Envoi moi un sms de que tu aimerai que je te fasse pour te faire plaisir.", pts:20 },
  { cat:'defi', text:"Embrasse-moi pendant 30 secondes, lentement, sans t'arrêter.", pts:15 },
  { cat:'defi', text:"Déshabille-moi d'un seul vêtement, à ta façon.", pts:20 },
  { cat:'defi', text:"Fais-moi un massage sensuel de 5 minutes, où tu veux.", pts:20 },
  { cat:'defi', text:"Décris-moi, les yeux dans les yeux, ce que tu as envie qu'on fasse au lit ce soir.", pts:25 },

  { cat:'gage', text:"Tu dois rester en sous-vêtements pour le reste de la soirée.", pts:20 },
  { cat:'gage', text:"Envoie-moi un message coquin maintenant, qui saura m'exiter à coup sûr", pts:15 },
  { cat:'gage', text:"Laisse-moi choisir ta tenue (ou ton absence de tenue) pour la suite de la soirée.", pts:20 },
  { cat:'gage', text:"Pendant 10 minutes, tu dois répondre à toutes mes demandes sans discuter.", pts:25 },

  // CONTENU PIMENTÉ (généré en variantes — modifiable/complétable depuis l'appli)
  { cat:'defi', text:"Embrasse les épaules pendant 2 minutes, lentement, sans t'arrêter.", pts:15 },
  { cat:'question', text:"Décris-moi au réveil, ce que tu rêves qu'on fasse ce soir.", pts:10 },
  { cat:'gage', text:"Tu dois me toucher le bas du dos à chaque fois que tu passes près de moi, pendant 30 secondes.", pts:25 },
  { cat:'gage', text:"Tu dois me toucher les épaules à chaque fois que tu passes près de moi, pendant 1 minute.", pts:15 },
  { cat:'defi', text:"Déshabille-moi d'un seul vêtement, à ta façon, au réveil.", pts:20 },
  { cat:'gage', text:"Tu dois me toucher les oreilles à chaque fois que tu passes près de moi, pendant 2 minutes.", pts:15 },
  { cat:'defi', text:"Mets en scène le/la patron(ne) et l'employé(e) jusqu'au prochain tour, sans sortir du personnage.", pts:25 },
  { cat:'defi', text:"Chuchote-moi à l'oreille un scénario où on serait rendez-vous où on se redécouvre pour la première fois, comme si on le vivait déjà.", pts:20 },
  { cat:'gage', text:"Pendant toute la soirée, tu dois répondre à toutes mes demandes sans discuter.", pts:20 },
  { cat:'gage', text:"Pendant toute la soirée, tu dois me décrire ce que tu ressens rien qu'en me regardant.", pts:20 },
  { cat:'gage', text:"Écris-moi ce que tu as envie qu'on fasse juste avant de dormir, et cache le mot quelque part que je dois trouver.", pts:15 },
  { cat:'defi', text:"Avec de l'huile de massage, fais-moi deviner où tu vas le poser sur le ventre, avant que je sente quoi que ce soit.", pts:25 },
  { cat:'defi', text:"Décris-moi à voix haute, les yeux dans les yeux, ce que tu as envie qu'on fasse [ … complète ici ].", pts:20 },
  { cat:'question', text:"Quel objet parmi une télécommande symbolique du pouvoir te tente le plus pour la suite de la soirée ?", pts:15 },
  { cat:'defi', text:"Emmène-moi sous la douche et prends les commandes pendant 1 minute.", pts:20 },
  { cat:'defi', text:"Chuchote-moi à l'oreille un scénario où on serait interrogatoire coquin, comme si on le vivait déjà.", pts:20 },
  { cat:'gage', text:"Pendant jusqu'au prochain tour, tu dois me décrire ce que tu ressens rien qu'en me regardant.", pts:20 },
  { cat:'gage', text:"Pour toute la soirée, c'est toi qui as de l'huile de massage et qui décides de ce qui se passe entre nous.", pts:15 },
  { cat:'defi', text:"Fais-moi un massage sensuel avec un foulard en guise de bandeau pendant 5 minutes.", pts:20 },
  { cat:'defi', text:"Embrasse le ventre jusqu'à demain matin, lentement, sans t'arrêter.", pts:15 },
  { cat:'defi', text:"Bande-moi les yeux avec un foulard en guise de bandeau et surprends-moi jusqu'à demain matin.", pts:20 },
  { cat:'gage', text:"Tiens le rôle de un rendez-vous où on se redécouvre pour la première fois jusqu'à demain matin, sans sortir du personnage.", pts:15 },
  { cat:'defi', text:"Emmène-moi dans le noir complet et prends les commandes pendant 30 secondes.", pts:20 },
  { cat:'defi', text:"Mets en scène un rendez-vous où on se redécouvre pour la première fois pendant 1 minute, sans sortir du personnage.", pts:25 },
  { cat:'gage', text:"Laisse-moi choisir ta tenue (ou ton absence de tenue) sous la douche.", pts:20 },
  { cat:'defi', text:"Mets en scène un interrogatoire coquin pendant 30 secondes, sans sortir du personnage.", pts:25 },
  { cat:'question', text:"Quel rôle parmi un rendez-vous où on se redécouvre pour la première fois te ferait le plus craquer si on le jouait ce soir ?", pts:20 },
  { cat:'gage', text:"Tiens le rôle de un jeu où je dis stop ou encore jusqu'au prochain tour, sans sortir du personnage.", pts:15 },
  { cat:'gage', text:"Pendant 2 minutes, tu dois répondre à toutes mes demandes sans discuter.", pts:20 },
  { cat:'question', text:"Qu'est-ce que je pourrais faire jusqu'à demain matin qui te rendrait complètement fou/folle ?", pts:20 },
  { cat:'defi', text:"Donne-moi 3 ordres que je dois suivre dans les jusqu'à demain matin qui suivent.", pts:20 },
  { cat:'defi', text:"Improvise un strip-tease de jusqu'à demain matin sur la musique de ton choix.", pts:15 },
  { cat:'defi', text:"Bande-moi les yeux avec un glaçon et surprends-moi jusqu'au prochain tour.", pts:25 },
  { cat:'defi', text:"Mets en scène un jeu où je dis stop ou encore jusqu'à demain matin, sans sortir du personnage.", pts:15 },
  { cat:'question', text:"Raconte-moi le souvenir le plus excitant qu'on ait vécu dans la cuisine.", pts:10 },
  { cat:'gage', text:"Tu dois m'embrasser sur le ventre toutes les 10 minutes, sans prévenir, pendant 1 minute.", pts:20 },
  { cat:'defi', text:"Déshabille-moi d'un seul vêtement, à ta façon, en pleine préparation du dîner.", pts:20 },
  { cat:'gage', text:"Pour jusqu'au prochain tour, c'est toi qui as une télécommande symbolique du pouvoir et qui décides de ce qui se passe entre nous.", pts:15 },
  { cat:'gage', text:"Pendant 30 secondes, tu dois me décrire ce que tu ressens rien qu'en me regardant.", pts:25 },
  { cat:'question', text:"Décris-moi juste avant de sortir, ce que tu rêves qu'on fasse ce soir.", pts:15 },
  { cat:'question', text:"Quelle tenue (ou absence de tenue) te donne le plus envie de moi juste avant de sortir ?", pts:20 },
  { cat:'gage', text:"Envoie-moi un message coquin juste avant de sortir, peu importe où tu es.", pts:20 },
  { cat:'defi', text:"Avec une plume, fais-moi deviner où tu vas le poser sur le bas du dos, avant que je sente quoi que ce soit.", pts:20 },
  { cat:'defi', text:"Mets en scène un jeu où je dis stop ou encore pour toute la soirée, sans sortir du personnage.", pts:25 },
  { cat:'question', text:"Si je te bandais les yeux 1 minute, qu'est-ce que tu espérerais que je fasse ?", pts:15 },
  { cat:'defi', text:"Improvise un strip-tease de jusqu'au prochain tour sur la musique de ton choix.", pts:20 },
  { cat:'gage', text:"Laisse-moi choisir ta tenue (ou ton absence de tenue) contre un mur.", pts:20 },
  { cat:'question', text:"Qu'est-ce que tu n'as jamais osé me demander au lit ?", pts:15 },
  { cat:'question', text:"Si je te bandais les yeux 2 minutes, qu'est-ce que tu espérerais que je fasse ?", pts:15 },
  { cat:'question', text:"Quel est l'endroit le plus inattendu où tu as envie qu'on le fasse ?", pts:10 },
  { cat:'gage', text:"Envoie-moi un message coquin au réveil, peu importe où tu es.", pts:15 },
  { cat:'gage', text:"Pendant 1 minute, tu dois répondre à toutes mes demandes sans discuter.", pts:25 },
  { cat:'gage', text:"Laisse-moi choisir ta tenue (ou ton absence de tenue) au lit, lumière allumée.", pts:20 },
  { cat:'gage', text:"Tiens le rôle de deux inconnus qui se rencontrent ce soir jusqu'au prochain tour, sans sortir du personnage.", pts:20 },
  { cat:'defi', text:"Embrasse le ventre pendant 2 minutes, lentement, sans t'arrêter.", pts:15 },
  { cat:'gage', text:"Tiens le rôle de un interrogatoire coquin pendant 2 minutes, sans sortir du personnage.", pts:20 },
  { cat:'question', text:"Sur une échelle de 1 à 10, à quel point as-tu envie de moi là, maintenant ?", pts:15 },
  { cat:'defi', text:"Avec une plume, fais-moi deviner où tu vas le poser sur le ventre, avant que je sente quoi que ce soit.", pts:20 },
  { cat:'defi', text:"Déshabille-moi d'un seul vêtement, à ta façon, juste avant de dormir.", pts:20 },
  { cat:'defi', text:"Emmène-moi contre un mur et prends les commandes jusqu'au prochain tour.", pts:25 },
  { cat:'defi', text:"Fais-moi un massage sensuel avec une télécommande symbolique du pouvoir jusqu'à demain matin.", pts:20 },
  { cat:'question', text:"Qu'est-ce que je pourrais faire jusqu'au prochain tour qui te rendrait complètement fou/folle ?", pts:15 },
  { cat:'defi', text:"Improvise un strip-tease de 5 minutes sur la musique de ton choix.", pts:15 },
  { cat:'defi', text:"Emmène-moi sous la douche et prends les commandes jusqu'au prochain tour.", pts:20 },
  { cat:'defi', text:"Emmène-moi contre un mur et prends les commandes pendant 30 secondes.", pts:20 },
  { cat:'defi', text:"Bande-moi les yeux avec une télécommande symbolique du pouvoir et surprends-moi pendant 30 secondes.", pts:25 },
  { cat:'defi', text:"Embrasse les épaules pour toute la soirée, lentement, sans t'arrêter.", pts:20 },
  { cat:'question', text:"Qu'est-ce que je pourrais faire pendant 5 minutes qui te rendrait complètement fou/folle ?", pts:20 },
  { cat:'defi', text:"Bande-moi les yeux avec une plume et surprends-moi pour toute la soirée.", pts:25 },
  { cat:'gage', text:"Laisse-moi choisir ta tenue (ou ton absence de tenue) dans le noir complet.", pts:15 },
  { cat:'defi', text:"Embrasse les oreilles jusqu'à demain matin, lentement, sans t'arrêter.", pts:20 },
  { cat:'gage', text:"Pour jusqu'au prochain tour, c'est toi qui as une plume et qui décides de ce qui se passe entre nous.", pts:25 },
  { cat:'question', text:"Raconte-moi le souvenir le plus excitant qu'on ait vécu dans le canapé.", pts:15 },
  { cat:'defi', text:"Avec de l'huile de massage, fais-moi deviner où tu vas le poser sur les épaules, avant que je sente quoi que ce soit.", pts:25 },
  { cat:'gage', text:"Envoie-moi un message coquin dès que tu rentres ce soir, peu importe où tu es.", pts:20 },
  { cat:'defi', text:"Fais-moi un massage sensuel avec un miroir pendant 2 minutes.", pts:25 },
  { cat:'question', text:"Raconte-moi le souvenir le plus excitant qu'on ait vécu au lit, lumière allumée.", pts:10 },
  { cat:'defi', text:"Donne-moi 3 ordres que je dois suivre dans les jusqu'au prochain tour qui suivent.", pts:15 },
  { cat:'defi', text:"Chuchote-moi à l'oreille un scénario inspiré de le/la patron(ne) et l'employé(e), comme si on le vivait déjà.", pts:20 },
  { cat:'defi', text:"Emmène-moi dans le canapé et prends les commandes pendant 1 minute.", pts:25 },
  { cat:'defi', text:"Embrasse la nuque jusqu'à demain matin, lentement, sans t'arrêter.", pts:25 },
  { cat:'question', text:"Quel rôle parmi le/la patron(ne) et l'employé(e) te ferait le plus craquer si on le jouait ce soir ?", pts:15 },
  { cat:'question', text:"Décris-moi juste avant de dormir, ce que tu rêves qu'on fasse ce soir.", pts:10 },
  { cat:'question', text:"Si je te bandais les yeux toute la soirée, qu'est-ce que tu espérerais que je fasse ?", pts:15 },
  { cat:'question', text:"Quelle tenue (ou absence de tenue) te donne le plus envie de moi dès que tu rentres ce soir ?", pts:20 },
  { cat:'gage', text:"Pour jusqu'à demain matin, c'est toi qui as un foulard en guise de bandeau et qui décides de ce qui se passe entre nous.", pts:20 },
  { cat:'question', text:"Quelle tenue (ou absence de tenue) te donne le plus envie de moi au réveil ?", pts:15 },
  { cat:'defi', text:"Emmène-moi dans la cuisine et prends les commandes pour toute la soirée.", pts:20 },
  { cat:'gage', text:"Écris-moi ce que tu as envie qu'on fasse en pleine préparation du dîner, et cache le mot quelque part que je dois trouver.", pts:20 },
  { cat:'defi', text:"Fais-moi un massage sensuel avec un glaçon pendant 1 minute.", pts:25 },
  { cat:'gage', text:"Tiens le rôle de deux inconnus qui se rencontrent ce soir pendant 2 minutes, sans sortir du personnage.", pts:25 },
  { cat:'defi', text:"Déshabille-moi d'un seul vêtement, à ta façon, dès que tu rentres ce soir.", pts:20 },
  { cat:'defi', text:"Bande-moi les yeux avec un foulard en guise de bandeau et surprends-moi pendant 5 minutes.", pts:25 },
  { cat:'question', text:"Si je te bandais les yeux 30 secondes, qu'est-ce que tu espérerais que je fasse ?", pts:10 },
  { cat:'question', text:"Décris la position dans laquelle tu as le plus envie de moi ce soir.", pts:15 },
  { cat:'question', text:"Raconte-moi le souvenir le plus excitant qu'on ait vécu dans le noir complet.", pts:15 },
  { cat:'gage', text:"Tiens le rôle de un rendez-vous où on se redécouvre pour la première fois pendant 30 secondes, sans sortir du personnage.", pts:25 },
  { cat:'defi', text:"Avec une télécommande symbolique du pouvoir, fais-moi deviner où tu vas le poser sur les épaules, avant que je sente quoi que ce soit.", pts:20 },
  { cat:'defi', text:"Emmène-moi dans le noir complet et prends les commandes pendant 2 minutes.", pts:25 },
  { cat:'defi', text:"Fais-moi un massage sensuel avec un miroir pendant 1 minute.", pts:25 },
  { cat:'question', text:"Raconte-moi le souvenir le plus excitant qu'on ait vécu contre un mur.", pts:20 },
  { cat:'defi', text:"Avec un glaçon, fais-moi deviner où tu vas le poser sur les épaules, avant que je sente quoi que ce soit.", pts:20 },
  { cat:'gage', text:"Pendant 1 minute, tu dois me décrire ce que tu ressens rien qu'en me regardant.", pts:15 },
  { cat:'gage', text:"Pendant jusqu'à demain matin, tu dois répondre à toutes mes demandes sans discuter.", pts:25 },
  { cat:'gage', text:"Pour jusqu'au prochain tour, c'est toi qui as de l'huile de massage et qui décides de ce qui se passe entre nous.", pts:15 },
  { cat:'question', text:"Qu'est-ce que je pourrais faire pendant 30 secondes qui te rendrait complètement fou/folle ?", pts:10 },
  { cat:'gage', text:"Laisse-moi choisir ta tenue (ou ton absence de tenue) dans la cuisine.", pts:20 },
  { cat:'question', text:"Quel objet parmi un foulard en guise de bandeau te tente le plus pour la suite de la soirée ?", pts:15 },
  { cat:'defi', text:"Improvise un strip-tease de 1 minute sur la musique de ton choix.", pts:25 },
  { cat:'gage', text:"Tu dois me toucher le ventre à chaque fois que tu passes près de moi, pour toute la soirée.", pts:20 },
];
const DEFAULT_CARDS = DEFAULT_CARDS_RAW.map((c, i) => ({ ...c, id: 'd' + i }));

const DEFAULT_REWARDS = [
  { pts: 50,  desc: "Un massage complet offert par l'autre" },
  { pts: 100, desc: "Choix du film/série de la soirée, sans contestation" },
  { pts: 200, desc: "Un petit-déjeuner au lit préparé avec amour" },
  { pts: 350, desc: "Une sortie ou activité surprise organisée par l'autre" },
  { pts: 500, desc: "Un week-end ou une grande sortie à planifier ensemble" },
];
