// Banque de cartes par défaut. category: 'question' | 'defi' | 'gage'
// Chaque carte porte un id figé ("d0", "d1"...) pour pouvoir être masquée/éditée
// depuis l'appli : il ne suit plus l'ordre du tableau, ne le renumérote jamais.
// Relecture : outils/export-cartes.py → Cartes.xlsx → outils/import-cartes.py.
const DEFAULT_CARDS_RAW = [
  // QUESTIONS (découverte / complicité)
  { id:'d0', cat:'question', text:"Quel est le souvenir le plus tendre que tu gardes de nous deux ?", pts:10 },
  { id:'d1', cat:'question', text:"Si on pouvait revivre une seule de nos journées ensemble, laquelle choisirais-tu ?", pts:10 },
  { id:'d2', cat:'question', text:"Quelle qualité chez moi t'a fait craquer au tout début ?", pts:10 },
  { id:'d3', cat:'question', text:"Quel est le rêve qu'on n'a pas encore réalisé ensemble ?", pts:15 },
  { id:'d4', cat:'question', text:"Quelle habitude de moi te fait sourire en cachette ?", pts:10 },
  { id:'d5', cat:'question', text:"Où aimerais-tu qu'on soit dans 5 ans ?", pts:15 },
  { id:'d6', cat:'question', text:"Quel petit geste du quotidien te fait te sentir aimé(e) ?", pts:10 },
  { id:'d7', cat:'question', text:"Raconte-moi un moment où tu as été fier/fière de moi.", pts:10 },
  { id:'d8', cat:'question', text:"Si on partait demain en voyage surprise, où voudrais-tu aller ?", pts:10 },
  { id:'d9', cat:'question', text:"Quel est ton souvenir préféré de notre rencontre ?", pts:10 },

  // DÉFIS (action, complicité physique ou créative)
  { id:'d10', cat:'defi', text:"Improvise une danse de 20 secondes sur la première chanson qui passe.", pts:15 },
  { id:'d11', cat:'defi', text:"Fais-moi un compliment sincère sans utiliser le mot 'beau/belle'.", pts:10 },
  { id:'d12', cat:'defi', text:"Fais-moi un massage des épaules pendant 2 minutes.", pts:15 },
  { id:'d13', cat:'defi', text:"Écris un petit mot doux que je garderai dans mon portefeuille.", pts:15 },
  { id:'d14', cat:'defi', text:"Prépare-moi une boisson surprise avec ce qu'on a dans les placards.", pts:15 },

  // GAGES (espiègles, légers)
  { id:'d15', cat:'gage', text:"Laisse l'autre choisir ta tenue pour demain.", pts:10 },
  { id:'d16', cat:'gage', text:"Envoie un message doux à ton/ta partenaire en plein milieu d'une activité du quotidien (sans prévenir).", pts:15 },
  { id:'d17', cat:'gage', text:"Tu dois répondre 'oui mon cœur' à tout pendant 30 minutes.", pts:15 },
  { id:'d18', cat:'gage', text:"Pas de téléphone pendant 1 heure, juste vous deux.", pts:20 },

  // CONTENU SENSUEL (mêlé aux catégories existantes — pour pimenter la soirée)
  { id:'d23', cat:'question', text:"Quel est ton fantasme que tu n'as encore jamais osé me dire ?", pts:20 },
  { id:'d24', cat:'question', text:"Quelle partie de mon corps préfères-tu, et pourquoi ?", pts:15 },
  { id:'d25', cat:'question', text:"Décris le moment où tu m'as désiré(e) le plus fort.", pts:15 },
  { id:'d26', cat:'question', text:"Qu'est-ce que tu aimerais qu'on essaie ensemble, qu'on n'a jamais fait ?", pts:20 },
  { id:'d27', cat:'question', text:"Sur une échelle de 1 à 10, à quel point as-tu envie de moi là, maintenant ?", pts:10 },

  { id:'d28', cat:'defi', text:"Murmure-moi à l'oreille ce que tu as envie de me faire ce soir.", pts:20 },
  { id:'d29', cat:'defi', text:"Embrasse-moi pendant 30 secondes, lentement, sans t'arrêter.", pts:15 },
  { id:'d30', cat:'defi', text:"Déshabille-moi d'un seul vêtement, à ta façon.", pts:20 },
  { id:'d31', cat:'defi', text:"Fais-moi un massage sensuel de 5 minutes, où tu veux.", pts:20 },
  { id:'d32', cat:'defi', text:"Décris-moi, les yeux dans les yeux, ce que tu as envie qu'on fasse au lit et qu'on a encore jamais fait.", pts:25 },

  { id:'d33', cat:'gage', text:"Tu dois rester en sous-vêtements pour le reste de la soirée.", pts:20 },
  { id:'d34', cat:'gage', text:"Envoie-moi un message coquin maintenant, peu importe où tu es.", pts:15 },
  { id:'d35', cat:'gage', text:"Laisse-moi choisir ta tenue (ou ton absence de tenue) pour la suite de la soirée.", pts:20 },
  { id:'d36', cat:'gage', text:"Pendant 10 minutes, tu dois répondre à toutes mes demandes sans discuter.", pts:25 },

  // CONTENU PIMENTÉ (généré en variantes — modifiable/complétable depuis l'appli)
  { id:'d37', cat:'defi', text:"Embrasse les épaules pendant 2 minutes, lentement, sans t'arrêter.", pts:15 },
  { id:'d38', cat:'question', text:"Décris-moi au réveil, ce que tu rêves qu'on fasse ce soir.", pts:10 },
  { id:'d39', cat:'gage', text:"Tu dois me toucher le bas du dos à chaque fois que tu passes près de moi, pendant 30 secondes.", pts:25 },
  { id:'d40', cat:'gage', text:"Tu dois me toucher les épaules à chaque fois que tu passes près de moi, pendant 1 minute.", pts:15 },
  { id:'d41', cat:'defi', text:"Déshabille-moi d'un seul vêtement, à ta façon, au réveil.", pts:20 },
  { id:'d42', cat:'gage', text:"Tu dois me toucher les oreilles à chaque fois que tu passes près de moi, pendant 2 minutes.", pts:15 },
  { id:'d43', cat:'defi', text:"Mets en scène le/la patron(ne) et l'employé(e) jusqu'au prochain tour, sans sortir du personnage.", pts:25 },
  { id:'d45', cat:'gage', text:"Pendant toute la soirée, tu dois répondre à toutes mes demandes sans discuter.", pts:20 },
  { id:'d46', cat:'gage', text:"Pendant toute la soirée, tu dois me décrire ce que tu ressens rien qu'en me regardant.", pts:20 },
  { id:'d47', cat:'gage', text:"Écris-moi ce que tu as envie qu'on fasse juste avant de dormir, et cache le mot quelque part que je dois trouver.", pts:15 },
  { id:'d48', cat:'defi', text:"Avec de l'huile de massage, fais-moi monter en température à ta façon.", pts:20 },
  { id:'d50', cat:'question', text:"Quel objet parmi une télécommande symbolique du pouvoir te tente le plus pour la suite de la soirée ?", pts:15 },
  { id:'d51', cat:'defi', text:"Sous la douche, ensemble, tu devras prendre l'initiative pour exciter l'autre.", pts:50 },
  { id:'d53', cat:'gage', text:"Pendant jusqu'au prochain tour, tu dois me décrire ce que tu ressens rien qu'en me regardant.", pts:20 },
  { id:'d54', cat:'gage', text:"Pour toute la soirée, c'est toi qui as de l'huile de massage et qui décides de ce qui se passe entre nous.", pts:15 },
  { id:'d55', cat:'defi', text:"Fais-moi un massage sensuel, du haut du dos jusqu'aux cuisses, sans oublier aucune zones.", pts:50 },
  { id:'d56', cat:'defi', text:"Fais-moi un massage sensuel, du haut du dos jusqu'aux cuisses, sans oublier aucune zones.", pts:50 },
  { id:'d57', cat:'defi', text:"Fais-moi un massage sensuel, du haut du dos jusqu'aux cuisses, sans oublier aucune zones.", pts:50 },
  { id:'d58', cat:'gage', text:"Tiens le rôle de un rendez-vous où on se redécouvre pour la première fois jusqu'à demain matin, sans sortir du personnage.", pts:15 },
  { id:'d60', cat:'defi', text:"Tu as 24h pour envoyer un nude !", pts:50 },
  { id:'d61', cat:'gage', text:"Laisse-moi choisir ta tenue (ou ton absence de tenue) sous la douche.", pts:20 },
  { id:'d63', cat:'question', text:"Quel rôle parmi un rendez-vous où on se redécouvre pour la première fois te ferait le plus craquer si on le jouait ce soir ?", pts:20 },
  { id:'d64', cat:'gage', text:"Tiens le rôle de un jeu où je dis stop ou encore jusqu'au prochain tour, sans sortir du personnage.", pts:15 },
  { id:'d65', cat:'gage', text:"Pendant 2 minutes, tu dois répondre à toutes mes demandes sans discuter.", pts:20 },
  { id:'d66', cat:'question', text:"Qu'est-ce que je pourrais faire jusqu'à demain matin qui te rendrait complètement fou/folle ?", pts:20 },
  { id:'d67', cat:'defi', text:"Brisez les tabous ! Tu dois raconter un fantasme que tu as depuis longtemps.", pts:20 },
  { id:'d68', cat:'defi', text:"Improvise un strip-Tease en finissant nu-e", pts:15 },
  { id:'d71', cat:'question', text:"Raconte-moi le souvenir le plus excitant qu'on ait vécu dans la cuisine.", pts:10 },
  { id:'d72', cat:'gage', text:"Tu dois m'embrasser sur le ventre toutes les 10 minutes, sans prévenir, pendant 1 minute.", pts:20 },
  { id:'d74', cat:'gage', text:"Pour jusqu'au prochain tour, c'est toi qui as une télécommande symbolique du pouvoir et qui décides de ce qui se passe entre nous.", pts:15 },
  { id:'d75', cat:'gage', text:"Pendant 30 secondes, tu dois me décrire ce que tu ressens rien qu'en me regardant.", pts:25 },
  { id:'d76', cat:'question', text:"Décris-moi juste avant de sortir, ce que tu rêves qu'on fasse ce soir.", pts:15 },
  { id:'d77', cat:'question', text:"Quelle tenue (ou absence de tenue) te donne le plus envie de moi juste avant de sortir ?", pts:20 },
  { id:'d78', cat:'gage', text:"Envoie-moi un message coquin juste avant de sortir, peu importe où tu es.", pts:20 },
  { id:'d81', cat:'question', text:"Si je te bandais les yeux 1 minute, qu'est-ce que tu espérerais que je fasse ?", pts:15 },
  { id:'d82', cat:'defi', text:"Improvise un strip-tease de jusqu'au prochain tour sur la musique de ton choix.", pts:20 },
  { id:'d83', cat:'gage', text:"Laisse-moi choisir ta tenue (ou ton absence de tenue) contre un mur.", pts:20 },
  { id:'d84', cat:'question', text:"Qu'est-ce que tu n'as jamais osé me demander au lit ?", pts:15 },
  { id:'d85', cat:'question', text:"Si je te bandais les yeux 2 minutes, qu'est-ce que tu espérerais que je fasse ?", pts:15 },
  { id:'d86', cat:'question', text:"Quel est l'endroit le plus inattendu où tu as envie qu'on le fasse ?", pts:10 },
  { id:'d87', cat:'gage', text:"Envoie-moi un message coquin au réveil, peu importe où tu es.", pts:15 },
  { id:'d88', cat:'gage', text:"Pendant 1 minute, tu dois répondre à toutes mes demandes sans discuter.", pts:25 },
  { id:'d89', cat:'gage', text:"Laisse-moi choisir ta tenue (ou ton absence de tenue) au lit, lumière allumée.", pts:20 },
  { id:'d90', cat:'gage', text:"Tiens le rôle de deux inconnus qui se rencontrent ce soir jusqu'au prochain tour, sans sortir du personnage.", pts:20 },
  { id:'d91', cat:'defi', text:"Embrasse le ventre pendant 2 minutes, lentement, sans t'arrêter.", pts:15 },
  { id:'d92', cat:'gage', text:"Tiens le rôle de un interrogatoire coquin pendant 2 minutes, sans sortir du personnage.", pts:20 },
  { id:'d93', cat:'question', text:"Sur une échelle de 1 à 10, à quel point as-tu envie de moi là, maintenant ?", pts:15 },
  { id:'d95', cat:'defi', text:"Déshabille-moi d'un seul vêtement, à ta façon, juste avant de dormir.", pts:20 },
  { id:'d96', cat:'defi', text:"Glisse ta main dans mes sous-vêtements en pleine nuit. Sans rien dire, commence à l'exciter.", pts:25 },
  { id:'d97', cat:'defi', text:"Fais-moi un massage sensuel avec une télécommande symbolique du pouvoir jusqu'à demain matin.", pts:20 },
  { id:'d98', cat:'question', text:"Qu'est-ce que je pourrais faire jusqu'au prochain tour qui te rendrait complètement fou/folle ?", pts:15 },
  { id:'d101', cat:'defi', text:"Embrasse moi de façon langoureuse.", pts:20 },
  { id:'d102', cat:'defi', text:"Bande-moi les yeux avec une télécommande symbolique du pouvoir et surprends-moi pendant 30 secondes.", pts:25 },
  { id:'d103', cat:'defi', text:"Masse le cuir-chevelu de ta / ton partenaire pendant 5 minutes.", pts:20 },
  { id:'d104', cat:'question', text:"Qu'est-ce que je pourrais faire pendant 5 minutes qui te rendrait complètement fou/folle ?", pts:20 },
  { id:'d106', cat:'gage', text:"Laisse-moi choisir ta tenue (ou ton absence de tenue) dans le noir complet.", pts:15 },
  { id:'d108', cat:'gage', text:"Pour jusqu'au prochain tour, c'est toi qui as une plume et qui décides de ce qui se passe entre nous.", pts:25 },
  { id:'d109', cat:'question', text:"Raconte-moi le souvenir le plus excitant qu'on ait vécu dans le canapé.", pts:15 },
  { id:'d110', cat:'defi', text:"Bande les yeux de ta / ton partenaire qui dois se mettre totalement nu-e. Tu réalise un massage complet de 15 minutes", pts:50 },
  { id:'d111', cat:'gage', text:"Envoie-moi un message coquin dès que tu rentres ce soir, peu importe où tu es.", pts:20 },
  { id:'d112', cat:'defi', text:"Fais-moi un massage sensuel d'une zone au choix.", pts:25 },
  { id:'d113', cat:'question', text:"Raconte-moi le souvenir le plus excitant qu'on ait vécu au lit, lumière allumée.", pts:10 },
  { id:'d116', cat:'defi', text:"Bande lui les yeux : tu dois réaliser un massage de 10 minutes de la zone de son choix.", pts:25 },
  { id:'d118', cat:'question', text:"Quel rôle parmi le/la patron(ne) et l'employé(e) te ferait le plus craquer si on le jouait ce soir ?", pts:15 },
  { id:'d119', cat:'question', text:"Décris-moi juste avant de dormir, ce que tu rêves qu'on fasse ce soir.", pts:10 },
  { id:'d120', cat:'question', text:"Si je te bandais les yeux toute la soirée, qu'est-ce que tu espérerais que je fasse ?", pts:15 },
  { id:'d121', cat:'question', text:"Quelle tenue (ou absence de tenue) te donne le plus envie de moi dès que tu rentres ce soir ?", pts:20 },
  { id:'d122', cat:'gage', text:"Pour jusqu'à demain matin, c'est toi qui as un foulard en guise de bandeau et qui décides de ce qui se passe entre nous.", pts:20 },
  { id:'d123', cat:'question', text:"Quelle tenue (ou absence de tenue) te donne le plus envie de moi au réveil ?", pts:15 },
  { id:'d124', cat:'defi', text:"Dans la cuisine, trouve un ustensil pour une fessée que tu vas recevoir.", pts:20 },
  { id:'d125', cat:'gage', text:"Écris-moi ce que tu as envie qu'on fasse en pleine préparation du dîner, et cache le mot quelque part que je dois trouver.", pts:20 },
  { id:'d127', cat:'gage', text:"Tiens le rôle de deux inconnus qui se rencontrent ce soir pendant 2 minutes, sans sortir du personnage.", pts:25 },
  { id:'d128', cat:'defi', text:"Déshabille-moi d'un seul vêtement, à ta façon, dès que tu rentres ce soir.", pts:20 },
  { id:'d129', cat:'defi', text:"Bande-moi les yeux avec un foulard en guise de bandeau et surprends-moi pendant 5 minutes.", pts:25 },
  { id:'d130', cat:'question', text:"Si je te bandais les yeux 30 secondes, qu'est-ce que tu espérerais que je fasse ?", pts:10 },
  { id:'d131', cat:'question', text:"Décris la position dans laquelle tu as le plus envie de moi ce soir.", pts:15 },
  { id:'d132', cat:'question', text:"Raconte-moi le souvenir le plus excitant qu'on ait vécu dans le noir complet.", pts:15 },
  { id:'d133', cat:'gage', text:"Tiens le rôle de un rendez-vous où on se redécouvre pour la première fois pendant 30 secondes, sans sortir du personnage.", pts:25 },
  { id:'d135', cat:'defi', text:"Emmène-moi dans le noir complet et prends les commandes pendant 2 minutes.", pts:25 },
  { id:'d136', cat:'defi', text:"Fais-moi un massage sensuel avec un miroir pendant 1 minute.", pts:25 },
  { id:'d137', cat:'question', text:"Raconte-moi le souvenir le plus excitant qu'on ait vécu contre un mur.", pts:20 },
  { id:'d139', cat:'gage', text:"Pendant 1 minute, tu dois me décrire ce que tu ressens rien qu'en me regardant.", pts:15 },
  { id:'d140', cat:'gage', text:"Pendant jusqu'à demain matin, tu dois répondre à toutes mes demandes sans discuter.", pts:25 },
  { id:'d141', cat:'gage', text:"Pour jusqu'au prochain tour, c'est toi qui as de l'huile de massage et qui décides de ce qui se passe entre nous.", pts:15 },
  { id:'d142', cat:'question', text:"Qu'est-ce que je pourrais faire pendant 30 secondes qui te rendrait complètement fou/folle ?", pts:10 },
  { id:'d143', cat:'gage', text:"Laisse-moi choisir ta tenue (ou ton absence de tenue) dans la cuisine.", pts:20 },
  { id:'d144', cat:'question', text:"Quel objet parmi un foulard en guise de bandeau te tente le plus pour la suite de la soirée ?", pts:15 },
  { id:'d145', cat:'defi', text:"Improvise un strip-tease de 1 minute sur la musique de ton choix.", pts:25 },
  { id:'d146', cat:'gage', text:"Tu dois me toucher le ventre à chaque fois que tu passes près de moi, pour toute la soirée.", pts:20 },

  // ANCIENNE CATÉGORIE "À DISTANCE" (fusionnée dans Défi) + DÉFIS PLUS DIRECTS
  { id:'d147', cat:'defi', text:"Envoie un message qui commence par 'J'ai hâte de...' et termine-le sincèrement.", pts:10 },
  { id:'d148', cat:'defi', text:"Envoie un message qui décrit ce que tu portes en ce moment, pendant ta pause.", pts:10 },
  { id:'d149', cat:'defi', text:"Envoie-moi une question coquine à laquelle je dois répondre dans l'heure.", pts:15 },
  { id:'d150', cat:'defi', text:"Prends les commandes : Guide sa main comme si c'était la tienne pour te donner du plaisir.", pts:25 },
  { id:'d151', cat:'defi', text:"Envoie une photo (habillé·e) et il / elle choisi le/les vêtement que tu enleveras pour la photo suivante.", pts:10 },
  { id:'d152', cat:'defi', text:"Décris par message un scénario qu'on pourrait jouer la prochaine fois qu'on sera seuls.", pts:15 },
  { id:'d153', cat:'defi', text:"Envoie un petit message coquin pour égailler la journée de l'autre !", pts:10 },
  { id:'d161', cat:'defi', text:"Décris par message, en 3 phrases, ce que tu as envie qu'on fasse à notre prochaine soirée ensemble.", pts:20 },
  { id:'d163', cat:'defi', text:"Envoie-moi une photo de ta main, avec une légende sur ce que tu voudrais qu'elle fasse pour te chauffer.", pts:15 },
  { id:'d164', cat:'defi', text:"Dis-moi, sans filtre, ce que tu ressens quand on vient juste de terminer notre relation sexuelle ?", pts:30 },
  { id:'d166', cat:'defi', text:"Décris-moi exactement ce que tu voudrais réaliser ensemble dans notre couple.", pts:25 },
  { id:'d167', cat:'defi', text:"Mime, sans un mot, ce que tu as envie qu'on fasse dans les 5 prochaines minutes.", pts:25 },
  { id:'d168', cat:'defi', text:"Raconte par message un souvenir précis de nous qui te fait sourire.", pts:15 },
  { id:'d169', cat:'defi', text:"Donne-moi 3 instructions précises pour te faire plaisir, que je dois suivre à la lettre.", pts:25 },
  { id:'d171', cat:'defi', text:"Montre-moi, sur toi-même, ce que tu aimerais que je fasse à ton sexe.", pts:25 },
  { id:'d173', cat:'defi', text:"Décris-moi par message un plaisir solitaire, comme si j'étais à côté de toi.", pts:10 },

  // CARTES HOT SUPPLÉMENTAIRES
  { id:'d179', cat:'gage', text:"Pendant 2 minutes, tu dois laisser ma main se balader sous tes vêtements sans jamais dire stop.", pts:30 },
  { id:'d180', cat:'defi', text:"Dans le lit, caresse mes fesses pendant 2 minutes de façon sensuel.", pts:30 },
  { id:'d183', cat:'defi', text:"Choisis un endroit sur toi, et dis-moi comment tu veux que je le touche. 30 secondes maximum.", pts:30 },
  { id:'d184', cat:'question', text:"Quel mot cru aimerais-tu que j'utilise pour t'exciter facilement ?", pts:25 },
  { id:'d185', cat:'question', text:"Quelle est la première chose que tu veux que je fasse à tes fesses si on se retrouve nus ?", pts:20 },
  { id:'d188', cat:'question', text:"Décris un fantasme que tu aimerais réaliser.", pts:25 },
  { id:'d189', cat:'defi', text:"Pendant 30 secondes, occupe-toi de mes tetons", pts:30 },
  { id:'d190', cat:'gage', text:"Pour 10 minutes, c'est moi qui décide de ta tenue (ou l'absence de tenue).", pts:25 },
  { id:'d192', cat:'gage', text:"Pour 30 secondes, c'est moi qui décide de ce qui arrive à tes fesses.", pts:25 },
  { id:'d195', cat:'gage', text:"L'adversaire choisis une position excitante, et tu dois la garder pendant 2 minutes", pts:25 },
  { id:'d198', cat:'question', text:"Si tu pouvais me demander quelques chosed'intime, sans aucune gêne ou limite, ca serait ?", pts:25 },
  { id:'d199', cat:'question', text:"Qu'est-ce qui pourrait t'exciter au point maximum en quelques minutes ? (Fantasme autorisé).", pts:20 },
  { id:'d204', cat:'gage', text:"Tu dois restersans sous-vetement jusqu'à ce qu'on aille se coucher.", pts:30 },
  { id:'d205', cat:'gage', text:"Décris comment tu aimes que l'on s'occupe de toi pour te faire jouir.", pts:30 },
  { id:'d207', cat:'question', text:"Si on devais changer une chose à nos relations sexuelles, tu dirais quoi ?", pts:20 },
  { id:'d210', cat:'defi', text:"Envoie-moi une photo d'une partie de ton corps de ton choix, juste pour faire monter la température.", pts:30 },
  { id:'d211', cat:'gage', text:"10 fessées déculottée, là, maintenant !", pts:30 },
  { id:'d212', cat:'question', text:"Décris la sensation exacte que tu ressens quand j'approche ma main entre tes cuisses.", pts:20 },
  { id:'d216', cat:'defi', text:"Sous la douche, je dois me faire plaisir avec le pommeau. Le partenaire doit vérifier !", pts:50 },
  { id:'d217', cat:'gage', text:"BONUS : 100 points en jeu ! Chacun doit faire tester le plaisir anale (doigts ou sextoy) à l'autre. A faire en meme temps, tendrement, selon la limite de chacun (lubrifiant recommandé).", pts:100 },
  { id:'d222', cat:'defi', text:"Envoie-moi un message qui décrit précisément une soirée parfaite juste nous 2.", pts:25 },

  // Cartes ajoutees depuis Cartes.xlsx
  { id:'d223', cat:'question', text:"On tombe sur un sexShop : on va voir ce qu'on y trouve ?", pts:10 },

  // Cartes ajoutees depuis Cartes-suggestions.xlsx (relecture du 25/08/2026)
  { id:'d224', cat:'gage', text:"Interdiction de dire « non » pendant les 15 prochaines minutes.", pts:15 },
  { id:'d225', cat:'gage', text:"Tu dois m'appeler par un petit surnom ridicule jusqu'à la fin de la soirée.", pts:10 },
  { id:'d226', cat:'gage', text:"Demain soir : ni télé ni téléphone, la soirée est à nous deux.", pts:20 },
  { id:'d227', cat:'gage', text:"Demain, tu dois m'embrasser à chaque fois que tu me croises.", pts:15 },
  { id:'d228', cat:'gage', text:"Demain, tu m'envoies un message à chaque fois que tu penses à moi (au moins 3 fois).", pts:15 },
  { id:'d229', cat:'gage', text:"Ce soir, tu me fais un compliment sincère à chaque fois que je te sers à boire.", pts:10 },
  { id:'d230', cat:'gage', text:"Tu gardes sur toi mon vêtement préféré jusqu'à ce qu'on aille se coucher.", pts:15 },
  { id:'d231', cat:'gage', text:"Interdiction de te rhabiller jusqu'à la fin de la partie.", pts:25 },
  { id:'d232', cat:'gage', text:"Tu dois me regarder dans les yeux la prochaine fois que tu jouis.", pts:40 },
  { id:'d233', cat:'gage', text:"Interdiction de faire le moindre bruit pendant 2 minutes, quoi que je te fasse.", pts:30 },
  { id:'d234', cat:'gage', text:"Tu me laisses écrire un mot sur ta peau, à l'endroit de mon choix.", pts:20 },
  { id:'d235', cat:'gage', text:"Position de levrette, tu dois ensuite enlever ton pantalon et sous-vetement délicatement dans l'autre.", pts:40 },
  { id:'d236', cat:'gage', text:"Tu as 1 minute pour m'envoyer une image porno trouvée sur le net.", pts:25 },
  { id:'d237', cat:'gage', text:"Au prochain tour, la carte piochée s'applique à toi ET à moi, en même temps.", pts:10 },
  { id:'d238', cat:'question', text:"Quelle petite habitude de notre quotidien tu ne voudrais changer pour rien au monde ?", pts:10 },
  { id:'d239', cat:'question', text:"Qu'est-ce que j'ai fait cette semaine qui t'a fait du bien, même si je ne l'ai pas remarqué ?", pts:10 },
  { id:'d240', cat:'question', text:"Si on avait un dimanche entier sans aucune obligation, tu le remplirais comment ?", pts:10 },
  { id:'d241', cat:'question', text:"Quelle est la chose qu'on repousse depuis trop longtemps et qu'il faudrait enfin faire ?", pts:15 },
  { id:'d242', cat:'question', text:"Qu'est-ce qui te manque le plus de moi quand on passe une journée séparés ?", pts:10 },
  { id:'d243', cat:'question', text:"Quel plat ou quelle odeur te ramène directement à un moment de nous deux ?", pts:10 },
  { id:'d244', cat:'question', text:"Dans 10 ans, à quoi ressemble une soirée parfaite chez nous ?", pts:15 },
  { id:'d245', cat:'question', text:"Qu'est-ce que tu n'oses pas me demander, de peur de me déranger ?", pts:15 },
  { id:'d246', cat:'question', text:"Quel compliment tu aimerais entendre plus souvent de ma part ?", pts:10 },
  { id:'d247', cat:'question', text:"De quelle dispute on a le plus appris, tous les deux ?", pts:15 },
  { id:'d248', cat:'question', text:"À quel moment de la journée tu me trouves le plus désirable, et pourquoi ?", pts:15 },
  { id:'d249', cat:'question', text:"Qu'est-ce qui te fait le plus d'effet : mes mains, ma bouche ou ma voix ?", pts:15 },
  { id:'d250', cat:'question', text:"Quelle limite tu aimerais qu'on repousse un peu, sans aller trop loin ?", pts:20 },
  { id:'d251', cat:'question', text:"Si je te disais « ce soir, tu ne décides de rien », ça te ferait quoi ?", pts:20 },
  { id:'d252', cat:'question', text:"Quel endroit de la maison n'a jamais servi et te tente vraiment ?", pts:20 },
  { id:'d253', cat:'question', text:"Tu préfères être surpris(e), ou savoir à l'avance ce que je vais te faire ?", pts:15 },
  { id:'d254', cat:'question', text:"Quelle scène qu'on a déjà vécue tu voudrais qu'on rejoue à l'identique ?", pts:20 },
  { id:'d255', cat:'question', text:"Y a-t-il un jouet ou un accessoire que tu aimerais qu'on essaie une fois ?", pts:25 },
  { id:'d256', cat:'question', text:"Ce qui t'excite le plus quand je te déshabille : la lenteur ou l'urgence ?", pts:20 },
  { id:'d257', cat:'question', text:"Raconte-moi ce que tu imagines quand tu penses à moi et que tu es seul(e).", pts:25 },
  { id:'d258', cat:'defi', text:"Demain matin, prépare-moi mon café (ou mon thé) sans que je le demande, et apporte-le-moi au lit.", pts:30 },
  { id:'d259', cat:'defi', text:"Bloque une date dans nos agendas pour une sortie à deux, là, tout de suite.", pts:15 },
  { id:'d260', cat:'defi', text:"Prends-moi dans tes bras pendant une minute complète, sans rien dire.", pts:10 },
  { id:'d261', cat:'defi', text:"Raconte-moi ta journée en ne gardant que les moments où tu as pensé à moi.", pts:10 },
  { id:'d262', cat:'defi', text:"Cuisine-moi quelque chose ce week-end, de A à Z, sans que je lève le petit doigt.", pts:20 },
  { id:'d263', cat:'defi', text:"Fais-moi rire en 30 secondes, par tous les moyens.", pts:10 },
  { id:'d264', cat:'defi', text:"Dis-moi trois choses que tu admires chez moi.", pts:15 },
  { id:'d265', cat:'defi', text:"Embrasse-moi dans le cou pendant 1 minute, sans jamais te servir de tes mains.", pts:20 },
  { id:'d266', cat:'defi', text:"Déshabille-moi entièrement, sans jamais toucher ma peau avec tes mains.", pts:30 },
  { id:'d267', cat:'defi', text:"Mets-toi derrière moi et caresse-moi partout. 2 minutes maximum.", pts:30 },
  { id:'d268', cat:'defi', text:"Occupe-toi de moi pendant 3 minutes sans que j'aie le droit de te toucher en retour.", pts:30 },
  { id:'d269', cat:'defi', text:"Tu as 24h pour m'envoyer une photo où tu te ferai plaisir avec un objet du quotidien.", pts:50 },
  { id:'d270', cat:'defi', text:"Partage moi un moment de plaisir solitaire, en face à face ou en vidéo selon les envies.", pts:100 },
  { id:'d271', cat:'defi', text:"Retire un vêtement à chaque fois que tu réponds « oui » à mes questions, pendant 5 questions.", pts:25 },
  { id:'d272', cat:'defi', text:"Assieds-toi sur moi tout habillé(e) et fais monter la température sans qu'un seul vêtement tombe.", pts:25 },
  { id:'d273', cat:'defi', text:"Mets-toi nu(e) et laisse-moi te regarder pendant 1 minute, sans rien faire d'autre.", pts:40 },
];
const DEFAULT_CARDS = DEFAULT_CARDS_RAW.map((c, i) => ({ ...c, id: c.id || 'd' + i }));

const DEFAULT_REWARDS = [
  { pts: 50,  desc: "Un massage complet offert par l'autre" },
  { pts: 100, desc: "Choix du film/série de la soirée, sans contestation" },
  { pts: 200, desc: "Un petit-déjeuner au lit préparé avec amour" },
  { pts: 350, desc: "Une sortie ou activité surprise organisée par l'autre" },
  { pts: 500, desc: "Un week-end ou une grande sortie à planifier ensemble" },
];
