// ====== BANQUE DE GAGES ALÉATOIRES (Défi Photo) ======
// Deux familles : « action » (quelque chose à faire) et « verite » (quelque
// chose à avouer). Le gage est écrit à l'envoi du défi par celui qui l'envoie,
// et réalisé par celui qui perd — les textes s'adressent donc au perdant.
//
// id : identifiant stable. Les gages déjà tirés sont retenus dans
//      rooms/$room/gagesVus et ne reviennent qu'une fois la liste épuisée.
// v  : date de relecture et validation par l'utilisateur.
//
// FICHIER GENERE — ne pas editer a la main.
// Pour modifier : python outils/export-gages.py, editer Gages-Photo.xlsx,
// puis python outils/import-gages.py

const GAGES_ALEATOIRES = [

  // ================= ACTIONS ================= (72)
  { id:'a001', type:'action', v:'2026-08-25', g:"Masse ton/ta partenaire du haut du dos jusqu'en bas des fesses, pendant 10 minutes, à l'huile, sans rien demander en retour. Il / Elle doit etre nu(e)." },
  { id:'a004', type:'action', v:'2026-08-25', g:"Pose-toi je gère les enfants ce soir !" },
  { id:'a006', type:'action', v:'2026-08-25', g:"Offre un massage des pieds, puis remonte lentement jusqu'aux partie intimes (inclus dans le massage!). Pentalon interdit !" },
  { id:'a010', type:'action', v:'2026-08-25', g:"Un doigt dans l'anus ! Le partenaire doit pouvoir regarder s'il le souhaite !" },
  { id:'a011', type:'action', v:'2026-08-25', g:"Caresse-toi devant ton/ta partenaire pendant 1 minute, qui a le droit de regarder mais pas de toucher." },
  { id:'a012', type:'action', v:'2026-08-25', g:"Tu devras envoyer un message détaillant un préliminaire que tu feras dès que possible." },
  { id:'a013', type:'action', v:'2026-08-25', g:"Action inversé ! A toit d'executer le gage : tu dois recevoir une fessée, vêtement baissé !" },
  { id:'a014', type:'action', v:'2026-08-25', g:"Enleve ton pantalon et sous-vetement, tu va prendre une fessée !" },
  { id:'a041', type:'action', v:'2026-08-25', g:"Passe 2 minutes à embrasser ton/ta partenaire sans que rien d'autre ne se passe." },
  { id:'a060', type:'action', v:'2026-08-25', g:"Fais l'amour en pleine nuit, meme si ton / ta partenaire dort encore." },
  { id:'a101', type:'action', v:'2026-08-25', g:"Montre ta poitrine à ton/ta partenaire pendant 1 minute." },
  { id:'a102', type:'action', v:'2026-08-25', g:"Montre tes fesses à ton/ta partenaire, maintenant." },
  { id:'a103', type:'action', v:'2026-08-25', g:"Enlève un vêtement de ton choix, tout de suite." },
  { id:'a104', type:'action', v:'2026-08-25', g:"Retire ton haut et reste ainsi jusqu'à la fin de la soirée." },
  { id:'a105', type:'action', v:'2026-08-25', g:"Envoie une photo osée de toi dès demain, sans prévenir." },
  { id:'a106', type:'action', v:'2026-08-25', g:"Envoie un message très cru à ton/ta partenaire demain, en pleine journée." },
  { id:'a107', type:'action', v:'2026-08-25', g:"Embrasse ton/ta partenaire dans le cou pendant 30 secondes." },
  { id:'a108', type:'action', v:'2026-08-25', g:"Embrasse ton/ta partenaire à pleine bouche pendant 1 minute, sans les mains." },
  { id:'a109', type:'action', v:'2026-08-25', g:"Passe la soirée sans sous-vêtements, et dis-le." },
  { id:'a110', type:'action', v:'2026-08-25', g:"Danse 30 secondes de façon suggestive, debout devant lui/elle." },
  { id:'a111', type:'action', v:'2026-08-25', g:"Murmure à l'oreille de ton/ta partenaire ce que tu lui ferais là, maintenant." },
  { id:'a112', type:'action', v:'2026-08-25', g:"Laisse ton/ta partenaire mettre sa main où il/elle veut pendant 1 minute." },
  { id:'a113', type:'action', v:'2026-08-25', g:"Montre-toi entièrement nu·e pendant 30 secondes." },
  { id:'a114', type:'action', v:'2026-08-25', g:"Envoie un message vocal de 10 secondes, très explicite." },
  { id:'a115', type:'action', v:'2026-08-25', g:"Fais un baiser dans le dos de ton/ta partenaire, de la nuque aux reins." },
  { id:'a116', type:'action', v:'2026-08-25', g:"Retire ton soutien-gorge ou ton caleçon sans enlever le reste." },
  { id:'a117', type:'action', v:'2026-08-25', g:"Laisse ton/ta partenaire te retirer un vêtement de son choix." },
  { id:'a118', type:'action', v:'2026-08-25', g:"Caresse ton/ta partenaire par-dessus ses vêtements pendant 1 minute." },
  { id:'a119', type:'action', v:'2026-08-25', g:"Mets-toi en sous-vêtements pour le reste de la soirée." },
  { id:'a120', type:'action', v:'2026-08-25', g:"Assieds-toi sur ton/ta partenaire pendant 1 minute, sans bouger." },
  { id:'a121', type:'action', v:'2026-08-25', g:"Mords doucement l'épaule de ton/ta partenaire." },
  { id:'a122', type:'action', v:'2026-08-25', g:"Lèche ou embrasse l'intérieur du poignet de ton/ta partenaire, lentement." },
  { id:'a123', type:'action', v:'2026-08-25', g:"Envoie demain matin un message décrivant ce dont tu as envie ce soir-là." },
  { id:'a124', type:'action', v:'2026-08-25', g:"Laisse ton/ta partenaire te bander les yeux pendant 2 minutes." },
  { id:'a125', type:'action', v:'2026-08-25', g:"Enlève ton pantalon et garde-le enlevé jusqu'au coucher." },
  { id:'a126', type:'action', v:'2026-08-25', g:"Fais un massage des épaules de 3 minutes, torse nu." },
  { id:'a127', type:'action', v:'2026-08-25', g:"Prends une photo de toi de façon à exciter l'autre, et envoie-la dès que possible." },
  { id:'a128', type:'action', v:'2026-08-25', g:"Embrasse le ventre de ton/ta partenaire pendant 30 secondes." },
  { id:'a129', type:'action', v:'2026-08-25', g:"Laisse ton/ta partenaire te deshabiller entièrement et observer ton corps pendant 2 minutes." },
  { id:'a130', type:'action', v:'2026-08-25', g:"Chuchote trois mots crus à l'oreille de ton/ta partenaire." },
  { id:'a131', type:'action', v:'2026-08-25', g:"Reste collé·e derrière ton/ta partenaire pendant 2 minutes, les mains autour de lui/elle." },
  { id:'a132', type:'action', v:'2026-08-25', g:"Fais glisser un glaçon sur la peau de ton/ta partenaire." },
  { id:'a133', type:'action', v:'2026-08-25', g:"Envoie un message demain qui commence par « ce soir, je veux… »." },
  { id:'a134', type:'action', v:'2026-08-25', g:"Retire un vêtement toutes les 5 minutes pendant un quart d'heure." },
  { id:'a135', type:'action', v:'2026-08-25', g:"Laisse ton/ta partenaire écrire un mot au feutre sur ta peau." },
  { id:'a136', type:'action', v:'2026-08-25', g:"Mets la lingerie ou le sous-vêtement que ton/ta partenaire préfère, ce soir." },
  { id:'a137', type:'action', v:'2026-08-25', g:"Embrasse ton/ta partenaire dans la nuque à chaque fois qu'il/elle se lève, ce soir." },
  { id:'a138', type:'action', v:'2026-08-25', g:"Fais un massage des mains de 2 minutes." },
  { id:'a139', type:'action', v:'2026-08-25', g:"Regarde ton/ta partenaire dans les yeux pendant 1 minute, sans parler, sans rigoler." },
  { id:'a140', type:'action', v:'2026-08-25', g:"Laisse ton/ta partenaire choisir ta tenue de nuit." },
  { id:'a141', type:'action', v:'2026-08-25', g:"Prends une douche ce soir en laissant la porte ouverte." },
  { id:'a142', type:'action', v:'2026-08-25', g:"Envoie une photo d'une partie de ton corps, au choix, dans l'heure." },
  { id:'a143', type:'action', v:'2026-08-25', g:"Laisse ton/ta partenaire te caresser 1 minute sans que tu bouges." },
  { id:'a144', type:'action', v:'2026-08-25', g:"Colle-toi contre ton/ta partenaire pendant qu'il/elle fait autre chose." },
  { id:'a145', type:'action', v:'2026-08-25', g:"Fais un compliment très cru sur le corps de ton/ta partenaire." },
  { id:'a147', type:'action', v:'2026-08-25', g:"Retire ce que tu veux, mais retire quelque chose. Maintenant." },
  { id:'a148', type:'action', v:'2026-08-25', g:"Dors sans rien porter cette nuit." },
  { id:'a149', type:'action', v:'2026-08-25', g:"Laisse ton/ta partenaire prendre une photo de toi comme il/elle le souhaite. Conserve ou supprime juste après, c'est entre vous !" },
  { id:'a150', type:'action', v:'2026-08-25', g:"Fais un câlin de 2 minutes, sans parler." },
  { id:'a151', type:'action', v:'2026-08-25', g:"Souffle doucement dans le cou de ton/ta partenaire pendant 20 secondes." },
  { id:'a152', type:'action', v:'2026-08-25', g:"Mets-toi à genoux devant ton/ta partenaire pendant 30 secondes." },
  { id:'a153', type:'action', v:'2026-08-25', g:"Envoie demain une photo de tes sous-vêtements du jour." },
  { id:'a154', type:'action', v:'2026-08-25', g:"Retire tes sous-vêtements et donne-les à ton/ta partenaire." },
  { id:'a155', type:'action', v:'2026-08-25', g:"Embrasse ton/ta partenaire partout sur le visage pendant 30 secondes." },
  { id:'a156', type:'action', v:'2026-08-25', g:"Laisse ton/ta partenaire poser sa main sous ton haut pendant 1 minute." },
  { id:'a157', type:'action', v:'2026-08-25', g:"Fais un massage du cuir chevelu de 2 minutes." },
  { id:'a158', type:'action', v:'2026-08-25', g:"Écris un mot coquin sur un papier et glisse-le dans sa poche." },
  { id:'a159', type:'action', v:'2026-08-25', g:"Reste en tenue légère et sers-lui à boire." },
  { id:'a160', type:'action', v:'2026-08-25', g:"Laisse ton/ta partenaire choisir une partie de ton corps à embrasser, et laisse-le/la faire." },
  { id:'a162', type:'action', v:'2026-08-25', g:"Enlève ton haut et laisse ton/ta partenaire te masser le dos 3 minutes." },
  { id:'a163', type:'action', v:'2026-08-25', g:"Mets une chanson et déshabille-toi le temps du refrain." },
  { id:'a165', type:'action', v:'2026-08-25', g:"Embrasse ton/ta partenaire en le/la plaquant doucement contre un mur." },

  // ================= VÉRITÉS ================= (47)
  { id:'v101', type:'verite', v:'2026-08-25', g:"Dis en une phrase ce dont tu as envie là, maintenant." },
  { id:'v102', type:'verite', v:'2026-08-25', g:"Combien de fois as-tu pensé au sexe aujourd'hui ?" },
  { id:'v103', type:'verite', v:'2026-08-25', g:"Nomme la partie du corps de ton/ta partenaire que tu préfères." },
  { id:'v104', type:'verite', v:'2026-08-25', g:"Dis un mot cru que tu aimerais entendre ce soir." },
  { id:'v105', type:'verite', v:'2026-08-25', g:"Quand as-tu eu le plus envie de lui/elle cette semaine ?" },
  { id:'v106', type:'verite', v:'2026-08-25', g:"Dis la première chose à laquelle tu as pensé en le/la voyant ce matin." },
  { id:'v107', type:'verite', v:'2026-08-25', g:"Note ton envie de lui/elle sur dix, tout de suite." },
  { id:'v108', type:'verite', v:'2026-08-25', g:"Dis un endroit de ton corps que tu voudrais qu'on embrasse maintenant." },
  { id:'v109', type:'verite', v:'2026-08-25', g:"Avoue la dernière fois que tu t'es touché·e en pensant à lui/elle." },
  { id:'v110', type:'verite', v:'2026-08-25', g:"Dis en trois mots ce que tu aimerais faire ce soir." },
  { id:'v111', type:'verite', v:'2026-08-25', g:"Quelle tenue de ton/ta partenaire te fait le plus d'effet ?" },
  { id:'v112', type:'verite', v:'2026-08-25', g:"Dis ce que tu voudrais qu'on te fasse là, tout de suite, qui te ferait plaisir" },
  { id:'v113', type:'verite', v:'2026-08-25', g:"Avoue si tu as eu envie de lui/elle aujourd'hui, et à quel moment." },
  { id:'v114', type:'verite', v:'2026-08-25', g:"Quel est le geste qui te fait craquer à chaque fois ?" },
  { id:'v115', type:'verite', v:'2026-08-25', g:"Dis une chose que tu n'as jamais osé demander." },
  { id:'v118', type:'verite', v:'2026-08-25', g:"Nomme un endroit de la maison où tu aimerais le/la faire." },
  { id:'v119', type:'verite', v:'2026-08-25', g:"Dis le dernier fantasme qui t'a traversé l'esprit." },
  { id:'v120', type:'verite', v:'2026-08-25', g:"Avoue si tu as regardé quelqu'un d'autre cette semaine." },
  { id:'v121', type:'verite', v:'2026-08-25', g:"Dis ce qui te ferait dire oui immédiatement." },
  { id:'v122', type:'verite', v:'2026-08-25', g:"Quel mot te met le plus mal à l'aise ? Dis-le à voix haute." },
  { id:'v123', type:'verite', v:'2026-08-25', g:"Dis en une phrase ce que tu préfères recevoir." },
  { id:'v125', type:'verite', v:'2026-08-25', g:"Dis ce qui t'excite le plus chez lui/elle, en un mot." },
  { id:'v126', type:'verite', v:'2026-08-25', g:"Préfères-tu diriger ou être dirigé·e ? Réponds franchement." },
  { id:'v127', type:'verite', v:'2026-08-25', g:"Dis à quelle fréquence tu voudrais vraiment, sans arrondir." },
  { id:'v128', type:'verite', v:'2026-08-25', g:"Nomme une pratique que tu voudrais essayer bientôt." },
  { id:'v129', type:'verite', v:'2026-08-25', g:"Dis ce que tu penses de ses sous-vêtements du jour." },
  { id:'v130', type:'verite', v:'2026-08-25', g:"Avoue si tu as déjà fait semblant d'être fatigué·e." },
  { id:'v131', type:'verite', v:'2026-08-25', g:"Dis le meilleur souvenir intime de ces trois derniers mois." },
  { id:'v132', type:'verite', v:'2026-08-25', g:"Quel est le premier mot qui te vient en pensant à son corps ?" },
  { id:'v134', type:'verite', v:'2026-08-25', g:"Avoue un endroit où tu as eu envie de lui/elle en public." },
  { id:'v135', type:'verite', v:'2026-08-25', g:"Dis ce que tu changerais dans ta façon de faire l'amour." },
  { id:'v136', type:'verite', v:'2026-08-25', g:"Nomme la partie de ton corps que tu préfères qu'on touche." },
  { id:'v140', type:'verite', v:'2026-08-25', g:"Quel est le compliment intime qui te fait le plus plaisir ?" },
  { id:'v141', type:'verite', v:'2026-08-25', g:"Dis une chose que tu adores et dont tu ne parles jamais." },
  { id:'v142', type:'verite', v:'2026-08-25', g:"Avoue si tu préfères le matin ou le soir, et pourquoi." },
  { id:'v143', type:'verite', v:'2026-08-25', g:"Dis le geste le plus excitant qu'il/elle t'ait fait." },
  { id:'v145', type:'verite', v:'2026-08-25', g:"Dis ce que tu voudrais entendre juste avant." },
  { id:'v147', type:'verite', v:'2026-08-25', g:"Dis ta position préférée, sans hésiter." },
  { id:'v148', type:'verite', v:'2026-08-25', g:"Quel accessoire te tente le plus ? Réponds en un mot." },
  { id:'v149', type:'verite', v:'2026-08-25', g:"Dis ce que tu trouves le plus sexy chez lui/elle en ce moment." },
  { id:'v150', type:'verite', v:'2026-08-25', g:"Avoue la dernière fois que tu as eu envie et que tu n'as rien dit." },
  { id:'v151', type:'verite', v:'2026-08-25', g:"Dis si tu aimerais qu'on soit plus bruyants." },
  { id:'v152', type:'verite', v:'2026-08-25', g:"Nomme le moment de la journée où tu as le plus envie." },
  { id:'v153', type:'verite', v:'2026-08-25', g:"Dis une chose que tu voudrais refaire exactement comme la dernière fois." },
  { id:'v154', type:'verite', v:'2026-08-25', g:"Avoue ce que tu regardes en premier quand il/elle se déshabille." },
  { id:'v155', type:'verite', v:'2026-08-25', g:"Avoue la dernière fois que tu t'es fait plaisir en solitaire." },
  { id:'v156', type:'verite', v:'2026-08-25', g:"Décrit comment tu te fait plaisir en solo ! Il faut des détails !" }
];
