// ====== BANQUE DE GAGES ALÉATOIRES (Défi Photo) ======
// Deux familles : « action » (quelque chose à faire) et « verite » (quelque
// chose à avouer). Le gage est écrit à l'envoi du défi par celui qui l'envoie,
// et réalisé par celui qui perd — les textes s'adressent donc au perdant.
//
// id : identifiant stable. Les gages déjà tirés sont retenus dans
//      rooms/$room/gagesVus et ne reviennent qu'une fois la liste épuisée.
// v  : date de relecture et validation par l'utilisateur.
//
// FICHIER GENERE — ne pas editer a la main.
// Pour modifier : python outils/export-gages.py, editer Gages-Photo.xlsx,
// puis python outils/import-gages.py

const GAGES_ALEATOIRES = [

  // ================= ACTIONS ================= (70)
  { id:'a001', type:'action', v:'', g:"Masse le dos de ton/ta partenaire pendant 10 minutes, à l'huile, sans rien demander en retour." },
  { id:'a002', type:'action', v:'', g:"Fais un strip-tease complet, en musique, sans te presser." },
  { id:'a003', type:'action', v:'', g:"Prends une douche à deux ce soir, et lave entièrement ton/ta partenaire." },
  { id:'a004', type:'action', v:'', g:"Laisse ton/ta partenaire choisir ta tenue, sous-vêtements compris, pour toute une soirée." },
  { id:'a005', type:'action', v:'', g:"Embrasse ton/ta partenaire pendant deux minutes sans interruption, sans les mains." },
  { id:'a006', type:'action', v:'', g:"Offre un massage des pieds, puis remonte lentement jusqu'où on te le demande." },
  { id:'a007', type:'action', v:'', g:"Envoie une photo osée de toi dans l'heure qui suit." },
  { id:'a008', type:'action', v:'', g:"Passe la soirée entière sans sous-vêtements, et préviens-en ton/ta partenaire." },
  { id:'a009', type:'action', v:'', g:"Laisse ton/ta partenaire te bander les yeux pendant vingt minutes, et accepte tout ce qui vient." },
  { id:'a010', type:'action', v:'', g:"Fais un cunnilingus ou une fellation, sans rien attendre en retour ce soir-là." },
  { id:'a011', type:'action', v:'', g:"Caresse-toi devant ton/ta partenaire, qui a le droit de regarder mais pas de toucher." },
  { id:'a012', type:'action', v:'', g:"Écris un message très explicite décrivant ce que tu feras ce soir, et envoie-le en pleine journée." },
  { id:'a013', type:'action', v:'', g:"Laisse ton/ta partenaire diriger entièrement le prochain rapport : tu ne décides de rien." },
  { id:'a014', type:'action', v:'', g:"Prépare la chambre : lumière tamisée, musique, et un moment rien que pour lui/elle." },
  { id:'a015', type:'action', v:'', g:"Embrasse chaque partie du corps de ton/ta partenaire, en commençant par les pieds." },
  { id:'a016', type:'action', v:'', g:"Fais durer les préliminaires vingt minutes minimum, sans aller plus loin avant." },
  { id:'a017', type:'action', v:'', g:"Laisse ton/ta partenaire t'attacher les mains pour toute la durée du prochain rapport." },
  { id:'a018', type:'action', v:'', g:"Réveille ton/ta partenaire demain matin par une caresse intime." },
  { id:'a019', type:'action', v:'', g:"Choisis un sextoy en ligne ensemble ce soir, et commande-le vraiment." },
  { id:'a020', type:'action', v:'', g:"Fais l'amour dans une autre pièce que la chambre, au choix de ton/ta partenaire." },
  { id:'a021', type:'action', v:'', g:"Mets la tenue ou la lingerie que ton/ta partenaire préfère, et garde-la toute la soirée." },
  { id:'a022', type:'action', v:'', g:"Danse un slow collé-serré dans le salon, jusqu'au bout de la chanson." },
  { id:'a023', type:'action', v:'', g:"Laisse ton/ta partenaire écrire un mot sur ton corps, à l'endroit de son choix." },
  { id:'a024', type:'action', v:'', g:"Offre un massage du cuir chevelu de dix minutes, en silence complet." },
  { id:'a025', type:'action', v:'', g:"Fais l'amour sans dire un seul mot, uniquement par gestes et regards." },
  { id:'a026', type:'action', v:'', g:"Laisse ton/ta partenaire décider de l'heure exacte du prochain rapport, et sois disponible." },
  { id:'a027', type:'action', v:'', g:"Prends une photo de toi que tu n'aurais jamais osé envoyer, et envoie-la." },
  { id:'a028', type:'action', v:'', g:"Sers le petit déjeuner au lit demain matin, en tenue légère." },
  { id:'a029', type:'action', v:'', g:"Embrasse ton/ta partenaire dans le cou pendant qu'il/elle fait autre chose, et n'arrête pas avant qu'on te le demande." },
  { id:'a030', type:'action', v:'', g:"Laisse ton/ta partenaire te déshabiller entièrement, sans bouger les mains." },
  { id:'a031', type:'action', v:'', g:"Réalise le fantasme que ton/ta partenaire nommera à voix haute, dans la limite du raisonnable." },
  { id:'a032', type:'action', v:'', g:"Passe une soirée entière sans téléphone, uniquement à deux." },
  { id:'a033', type:'action', v:'', g:"Fais un massage intégral, de la nuque aux orteils, sans sauter une zone." },
  { id:'a034', type:'action', v:'', g:"Réserve une nuit à l'hôtel pour vous deux, dans le mois qui vient." },
  { id:'a035', type:'action', v:'', g:"Laisse ton/ta partenaire choisir la position du prochain rapport, sans discuter." },
  { id:'a036', type:'action', v:'', g:"Murmure trois choses très crues à l'oreille de ton/ta partenaire, ce soir." },
  { id:'a037', type:'action', v:'', g:"Prends un bain à deux, bougies comprises." },
  { id:'a038', type:'action', v:'', g:"Fais l'amour avec la lumière allumée, si ce n'est pas ton habitude." },
  { id:'a039', type:'action', v:'', g:"Laisse ton/ta partenaire te filmer ou te photographier pendant un moment intime, et effacez ensemble après." },
  { id:'a040', type:'action', v:'', g:"Offre un moment de plaisir avec les mains uniquement, jusqu'au bout." },
  { id:'a041', type:'action', v:'', g:"Passe vingt minutes à embrasser ton/ta partenaire sans que rien d'autre ne se passe." },
  { id:'a042', type:'action', v:'', g:"Prépare son plat préféré, et sers-le en tenue de ton choix… la plus légère possible." },
  { id:'a043', type:'action', v:'', g:"Laisse ton/ta partenaire te donner un ordre par message, à n'importe quel moment de la journée." },
  { id:'a044', type:'action', v:'', g:"Fais l'amour le matin avant de partir travailler, quitte à mettre le réveil plus tôt." },
  { id:'a045', type:'action', v:'', g:"Écris à la main une lettre décrivant ce que tu aimes le plus faire avec lui/elle, et donne-la." },
  { id:'a046', type:'action', v:'', g:"Laisse-toi guider les yeux fermés dans toute la maison, sans poser de question." },
  { id:'a047', type:'action', v:'', g:"Offre un massage assis, derrière ton/ta partenaire, pendant qu'il/elle regarde un épisode entier." },
  { id:'a048', type:'action', v:'', g:"Fais durer un baiser dans l'ascenseur, la voiture ou un lieu inhabituel." },
  { id:'a049', type:'action', v:'', g:"Ce soir, c'est toi qui prends entièrement le contrôle, du début à la fin." },
  { id:'a050', type:'action', v:'', g:"Laisse ton/ta partenaire choisir un accessoire à utiliser sur toi." },
  { id:'a051', type:'action', v:'', g:"Envoie un message vocal très explicite pendant la journée." },
  { id:'a052', type:'action', v:'', g:"Fais l'amour sans jamais rompre le contact visuel." },
  { id:'a053', type:'action', v:'', g:"Passe la nuit entière collé·e à ton/ta partenaire, sans t'écarter." },
  { id:'a054', type:'action', v:'', g:"Prépare une surprise coquine pour le week-end, sans en dire un mot avant." },
  { id:'a055', type:'action', v:'', g:"Laisse ton/ta partenaire te caresser pendant dix minutes sans que tu aies le droit de bouger." },
  { id:'a056', type:'action', v:'', g:"Fais un massage à quatre mains… enfin, à deux mains, mais avec toute ton attention." },
  { id:'a057', type:'action', v:'', g:"Choisis et mets un parfum qui rend ton/ta partenaire fou/folle, pour la soirée." },
  { id:'a058', type:'action', v:'', g:"Recommence exactement le premier baiser que vous vous êtes donné." },
  { id:'a059', type:'action', v:'', g:"Laisse ton/ta partenaire décider si tu as le droit de jouir ce soir." },
  { id:'a060', type:'action', v:'', g:"Fais l'amour dans le noir complet, sans un bruit, en pleine nuit." },
  { id:'a061', type:'action', v:'', g:"Offre un moment de plaisir uniquement avec la bouche, aussi longtemps qu'on te le demande." },
  { id:'a062', type:'action', v:'', g:"Prends l'initiative trois fois cette semaine, sans attendre de signal." },
  { id:'a063', type:'action', v:'', g:"Laisse ton/ta partenaire fouiller ton téléphone pendant cinq minutes, sans regarder." },
  { id:'a064', type:'action', v:'', g:"Habille-toi ce soir uniquement de ce que ton/ta partenaire aura choisi dans ton armoire." },
  { id:'a065', type:'action', v:'', g:"Fais couler un bain, prépare tout, et occupe-toi entièrement de ton/ta partenaire dedans." },
  { id:'a066', type:'action', v:'', g:"Embrasse ton/ta partenaire à pleine bouche en public, sans prévenir." },
  { id:'a067', type:'action', v:'', g:"Consacre une soirée entière au plaisir de l'autre, sans rien recevoir." },
  { id:'a068', type:'action', v:'', g:"Laisse ton/ta partenaire écrire la suite du programme de la soirée sur un papier, et suis-le à la lettre." },
  { id:'a069', type:'action', v:'', g:"Fais l'amour dans la cuisine, ce soir." },
  { id:'a070', type:'action', v:'', g:"Reste nu·e pendant une heure à la maison, en vaquant normalement à tes occupations." },

  // ================= VÉRITÉS ================= (50)
  { id:'v001', type:'verite', v:'', g:"Avoue le fantasme que tu n'as jamais osé formuler à voix haute." },
  { id:'v002', type:'verite', v:'', g:"Dis à quel moment précis tu as eu le plus envie de ton/ta partenaire cette semaine." },
  { id:'v003', type:'verite', v:'', g:"Raconte le rapport dont tu te souviens le mieux, et pourquoi." },
  { id:'v004', type:'verite', v:'', g:"Dis honnêtement ce qui te manque le plus dans votre vie sexuelle." },
  { id:'v005', type:'verite', v:'', g:"Avoue une pratique qui te tente et dont tu n'as jamais parlé." },
  { id:'v006', type:'verite', v:'', g:"Dis quelle partie du corps de ton/ta partenaire te fait le plus d'effet, et pourquoi." },
  { id:'v007', type:'verite', v:'', g:"Raconte la dernière fois que tu as pensé à lui/elle dans un moment intime, seul·e." },
  { id:'v008', type:'verite', v:'', g:"Avoue si tu as déjà simulé, et dans quelles circonstances." },
  { id:'v009', type:'verite', v:'', g:"Dis ce que tu aimerais qu'on te fasse et que tu n'oses pas demander." },
  { id:'v010', type:'verite', v:'', g:"Raconte le lieu le plus improbable où tu as eu envie de le/la faire." },
  { id:'v011', type:'verite', v:'', g:"Dis ce qui te coupe le plus l'envie, sans édulcorer." },
  { id:'v012', type:'verite', v:'', g:"Avoue le vêtement de ton/ta partenaire qui t'excite le plus, même s'il est banal." },
  { id:'v013', type:'verite', v:'', g:"Note votre vie sexuelle sur dix, et explique ce qui manque pour arriver à dix." },
  { id:'v014', type:'verite', v:'', g:"Raconte ce que tu voudrais essayer une fois dans ta vie, même si ça n'arrivera jamais." },
  { id:'v015', type:'verite', v:'', g:"Dis à quel moment tu as trouvé ton/ta partenaire le/la plus désirable, toutes années confondues." },
  { id:'v016', type:'verite', v:'', g:"Avoue si tu as déjà eu envie de quelqu'un d'autre depuis que vous êtes ensemble." },
  { id:'v017', type:'verite', v:'', g:"Raconte le geste le plus excitant qu'on t'ait fait, sans citer de nom." },
  { id:'v018', type:'verite', v:'', g:"Dis ce que tu préfères : donner ou recevoir, et pourquoi vraiment." },
  { id:'v019', type:'verite', v:'', g:"Avoue une chose que tu fais au lit uniquement pour lui/elle faire plaisir." },
  { id:'v020', type:'verite', v:'', g:"Dis la fréquence que tu voudrais réellement, sans arrondir." },
  { id:'v021', type:'verite', v:'', g:"Raconte ta plus grosse frustration au lit, celle dont tu n'as jamais parlé." },
  { id:'v022', type:'verite', v:'', g:"Avoue si tu as déjà regardé un film pour adultes en pensant à vous deux." },
  { id:'v023', type:'verite', v:'', g:"Dis ce qui t'a le plus surpris·e chez ton/ta partenaire, intimement." },
  { id:'v024', type:'verite', v:'', g:"Raconte le moment où tu as eu le plus peur d'être surpris·e." },
  { id:'v025', type:'verite', v:'', g:"Avoue ce que tu penses vraiment des jeux de domination." },
  { id:'v026', type:'verite', v:'', g:"Dis ce que tu ne ferais jamais, quoi qu'il arrive, et pourquoi." },
  { id:'v027', type:'verite', v:'', g:"Raconte la fois où tu as eu le plus envie et où il ne s'est rien passé." },
  { id:'v028', type:'verite', v:'', g:"Avoue quel mot ou quelle phrase te fait le plus d'effet quand on te le murmure." },
  { id:'v029', type:'verite', v:'', g:"Dis honnêtement si tu penses parfois à autre chose pendant l'amour." },
  { id:'v030', type:'verite', v:'', g:"Raconte ce que tu aimerais qu'on te fasse au réveil." },
  { id:'v031', type:'verite', v:'', g:"Avoue la chose la plus osée que tu aies faite avant votre rencontre." },
  { id:'v032', type:'verite', v:'', g:"Dis ce qui te ferait dire oui à absolument n'importe quoi, ce soir." },
  { id:'v033', type:'verite', v:'', g:"Raconte le meilleur souvenir intime de votre première année ensemble." },
  { id:'v034', type:'verite', v:'', g:"Avoue si tu préférerais plus de tendresse ou plus d'intensité." },
  { id:'v035', type:'verite', v:'', g:"Dis quelle position tu voudrais abandonner définitivement." },
  { id:'v036', type:'verite', v:'', g:"Raconte ce que tu ressens exactement quand ton/ta partenaire prend l'initiative." },
  { id:'v037', type:'verite', v:'', g:"Avoue si tu as déjà fait semblant d'être fatigué·e pour éviter un rapport." },
  { id:'v038', type:'verite', v:'', g:"Dis ce que tu changerais dans ta propre façon de faire l'amour." },
  { id:'v039', type:'verite', v:'', g:"Raconte le compliment intime qui t'a le plus marqué·e." },
  { id:'v040', type:'verite', v:'', g:"Avoue combien de fois tu as pensé au sexe aujourd'hui." },
  { id:'v041', type:'verite', v:'', g:"Dis ce que tu voudrais qu'on t'interdise, juste pour l'attente." },
  { id:'v042', type:'verite', v:'', g:"Raconte le moment de la journée où tu as le plus envie, et pourquoi ça ne se voit pas." },
  { id:'v043', type:'verite', v:'', g:"Avoue si tu as déjà eu envie de proposer une troisième personne." },
  { id:'v044', type:'verite', v:'', g:"Dis ce qui t'excite chez ton/ta partenaire en dehors du physique." },
  { id:'v045', type:'verite', v:'', g:"Raconte une chose que tu as vue ou lue et que tu voudrais reproduire." },
  { id:'v046', type:'verite', v:'', g:"Avoue le plus long moment où tu as tenu sans rien dire de ton envie." },
  { id:'v047', type:'verite', v:'', g:"Dis ce que tu préfères dans la façon dont ton/ta partenaire t'embrasse." },
  { id:'v048', type:'verite', v:'', g:"Raconte ce que tu ferais si vous aviez une maison vide pendant trois jours." },
  { id:'v049', type:'verite', v:'', g:"Avoue la chose la plus gênante qui te soit arrivée pendant l'amour." },
  { id:'v050', type:'verite', v:'', g:"Dis, sans détour, ce que tu veux qu'on te fasse ce soir." }
];
